teamforus/forus-backend

.env.example, app/Services/BunqService/BunqService.php
v0.0.3 was pushed to staging and production last moday. The only addition to the release is allowing multiple bunq ip adresses.
=> allow to add additional ip addresses to bunq

.env.example, app/Services/BunqService/BunqService.php
As v0.0.3 was pushed early to master last week on the monday, this release now only contains a bug fix for bunq integrations.
changelog:
product vouchers
bunq integrations
=> release v0.0.3

app/Http/Middleware/TrustProxies.php, app/Services/Forus/MailNotification/MailService.php
=> Release v0.0.6c

.env.example, app/Http/Controllers/Api/Platform/OfficesController.php, app/Http/Controllers/Api/Platform/Vouchers/TransactionsController.php, app/Http/Controllers/Api/Platform/VouchersController.php, app/Http/Requests/Api/Platform/Vouchers/Transactions/StoreVoucherTransactionRequest.php, app/Http/Resources/FundResource.php, app/Http/Resources/ProductResource.php, app/Http/Resources/Provider/ProviderVoucherResource.php, app/Http/Resources/Provider/ProviderVoucherTransactionResource.php, app/Http/Resources/Sponsor/SponsorVoucherTransactionResource.php, app/Http/Resources/VoucherResource.php, app/Http/Resources/VoucherTransactionResource.php, app/Models/Fund.php, app/Models/Product.php, app/Models/Voucher.php, app/Providers/RouteServiceProvider.php, app/helpers.php, routes/api-platform.php
- Fix voucher amount and address
- Fix voucher amount validation rule
- Update API currency format
=> Release v0.0.7

app/Services/Forus/Mailer/MailerServiceProvider.php
Reverts teamforus/forus-backend#41
=> Revert "Update MailerServiceProvider.php"

config/forus/features/dashboard.php, config/forus/features/webshop.php
Config to disable product vouchers
=> Release v0.0.8

app/Http/Resources/Provider/ProviderVoucherTransactionResource.php, app/Http/Resources/VoucherTransactionResource.php
Add fund and (provider) organization logo to transactions request.
=> Transaction logo #374

app/Http/Controllers/Api/Platform/Organizations/Funds/FundProviderController.php
Notification: disable provider rejection e-mail #434
=> Notification: disable provider rejection e-mail #434

app/Http/Controllers/Api/Platform/Organizations/FundsController.php, app/Models/Fund.php
Added fix fund state cron task
=> Bugfix for release v0.1.3

app/Http/Controllers/Api/Platform/PrevalidationController.php, app/Http/Requests/Api/Platform/SearchPrevalidationsRequest.php, app/Http/Resources/FundResource.php, app/Http/Resources/PrevalidationResource.php, app/Models/Fund.php, app/Models/FundConfig.php, app/Models/FundFormula.php, app/Models/Implementation.php, app/Models/Prevalidation.php, app/Models/Voucher.php, app/Policies/FundPolicy.php, app/Rules/PrevalidationDataRule.php, database/migrations/2018_12_26_064039_add_fund_configs_csv_primary_key.php, database/migrations/2018_12_26_064055_add_fund_id_to_prevalidations.php, database/migrations/2018_12_27_063056_create_fund_formulas_table.php, resources/lang/nl/validation.php
Changelog:
add fund_formula,
customizable prevalidation pk
csv validation
prevalidation filters
fix for applying to fund
fix amount on transaction mail
=> Add fund formula update to release

app/Http/Controllers/Api/IdentityController.php
Fix for ios/android compatibility
=> Compatibility fix convert auth_code to integer

app/Http/Controllers/Api/Platform/PrevalidationController.php, app/Http/Requests/Api/Platform/SearchPrevalidationsRequest.php, app/Http/Resources/PrevalidationResource.php, app/Models/Prevalidation.php, database/migrations/2018_12_26_064055_add_fund_id_to_prevalidations.php, database/migrations/2019_01_02_223611_prevalidations_add_exported_flag.php, routes/api-platform.php
Also move csv generation from front-end to back-end
=> CSV upload: add status for 'exported' #580

app/Http/Controllers/Api/Platform/VouchersController.php, app/Http/Requests/Api/Platform/Vouchers/ShareProductVoucherRequest.php, app/Models/Voucher.php, app/Services/Forus/MailNotification/MailService.php, routes/api-platform.php
[Webshop update: share button on productvoucher page #189](https://github.com/teamforus/forus/issues/189)
=> Webshop update: share button on productvoucher page #189

app/Http/Resources/FundResource.php, app/Models/Fund.php
[Show voucher amount and start / end date #598](https://github.com/teamforus/forus/issues/598)
=> Show voucher amount and start / end date #598

app/Models/Fund.php, app/Services/Forus/MailNotification/MailService.php
Fund update: send providers mail that they can expect customers [#453](https://github.com/teamforus/forus/issues/453)
=> Feature send providers mail that they can expect customers

app/Http/Resources/ProductResource.php, app/Models/Product.php, app/Providers/RouteServiceProvider.php, routes/api-platform.php
Let the provider set the product to deleted instead of removing it from db [#707](https://github.com/teamforus/forus/issues/707)
=> Fix deleted products

app/Http/Resources/FundResource.php, app/Policies/OfficePolicy.php
financial dashboard: total amount on fund fix [#612](https://github.com/teamforus/forus/issues/612)
Give the users (provider) the option to delete an office (if there is more than 1) [#705](https://github.com/teamforus/forus/issues/705)
=> Fix total amount on fund, fix delete offices

app/Console/Commands/NotifyAboutVoucherExpireCommand.php, app/Console/Kernel.php, app/Http/Controllers/Api/Platform/VouchersController.php, app/Models/Voucher.php, app/Services/Forus/MailNotification/MailService.php
Fund update: send mail to citizen that his voucher is about to expire. [#455](https://github.com/teamforus/forus/issues/455)
Share product: add option to also mail to your self share product [#660](https://github.com/teamforus/forus/issues/660)
=> Send mail to citizen that his voucher is about to expire

app/Models/VoucherTransaction.php
Transactions list: provider/sponsor sort by newest date time to oldest [#730](https://github.com/teamforus/forus/issues/730)
=> Fix transactions list - order by latest

app/Console/Commands/NotifyAboutReachedNotificationFundAmount.php, app/Console/Kernel.php, app/Http/Controllers/Api/Platform/Organizations/FundsController.php, app/Http/Requests/Api/Platform/Organizations/Funds/StoreFundRequest.php, app/Http/Requests/Api/Platform/Organizations/Funds/UpdateFundRequest.php, app/Http/Resources/FundResource.php, app/Models/Fund.php, app/Services/Forus/MailNotification/MailService.php, database/migrations/2019_01_22_095221_add_notification_at_funds.php
fund update: add e-mail notification that fund saldo is almost 0 [#487](https://github.com/teamforus/forus/issues/487)
=> Feature notify fund saldo

app/Http/Controllers/Api/Platform/Organizations/ProductsController.php
Server notification: new_product_added.tpl is send to the sponsor and the provider. [#710](https://github.com/teamforus/forus/issues/710)
=> Fix sponsor notification about new product created

app/Providers/RouteServiceProvider.php, database/seeds/Lorem/LoremDbSeeder.php, routes/api-platform.php
Lorem Ipsum seeder for Westerkwartier implementation
=> Westerkwartier implementation

app/Models/FundTopUp.php, resources/lang/en/bunq.php, resources/lang/nl/bunq.php
BUNQ: make bunq code shorter [#658](https://github.com/teamforus/forus/issues/658)
translate or remove 'fund' in description of BUNQ transaction [#668](https://github.com/teamforus/forus/issues/668)
=> Fix bunq code and fund translations

database/migrations/2019_02_12_153151_change_website_column_organization_table.php
Fix website can't be null [#765](https://github.com/teamforus/forus/issues/765)
=> Fix website can't be null #765

app/Http/Controllers/Api/Platform/Organizations/Funds/FundProviderController.php, app/Http/Controllers/Api/Platform/Organizations/FundsController.php
Adding product categories to financial dashboard, show total amounts per category [#754](https://github.com/teamforus/forus/issues/754)
=> Added product category to financial dashboard

resources/lang/nl/export.php
=> added new labels for export fixes teamforus/forus#782

app/Http/Controllers/Api/Platform/Organizations/FundsController.php
removed is not ! on auth->id to return fundresource when user is authenticated and authorized
=> adjusted fundcontroller

app/Http/Controllers/Api/Platform/Validator/ValidatorRequestController.php, app/Http/Controllers/Api/Platform/ValidatorsController.php, app/Http/Resources/Validator/ValidatorRequestResource.php, app/Models/ValidatorRequest.php, config/forus/features/dashboard.php
@dev-rminds is this ready for testing?
=> Epic: validator dashboard

resources/lang/nl/validation.php
https://github.com/teamforus/forus/issues/1054
=> added business type validation translation

app/Http/Controllers/Api/IdentityController.php, app/Http/Controllers/Api/Platform/Organizations/EmployeesController.php, app/Http/Middleware/ClientTypeMiddleware.php, app/Http/Requests/Api/Platform/Organizations/Employees/StoreEmployeeRequest.php, app/Mail/User/EmployeeAddedMail.php, app/Models/Role.php, app/Policies/FundPolicy.php, app/Services/Forus/Notification/NotificationService.php, database/migrations/2019_10_10_210428_add_view_funds_permission.php, database/seeds/PermissionsTableSeeder.php, database/seeds/RolePermissionsTableSeeder.php, resources/lang/nl/mails/implementations/general/email_employee.php, resources/views/emails/user/employee_added.blade.php
https://github.com/teamforus/forus/issues/459
=> Invite employees of sponsor/provider via employee/access level page

app/Http/Resources/FundCriterionResource.php, app/Models/Fund.php, app/Models/FundCriterion.php, database/migrations/2019_10_30_101955_add_fund_criteria_settings.php
https://github.com/teamforus/forus/issues/1034
=> Fund criteria, add new fields

app/Http/Controllers/Api/Platform/Organizations/Provider/FundProviderController.php
https://github.com/teamforus/forus/issues/1122
=> Sort available funds by newest

app/Http/Controllers/Api/Platform/FundsController.php, app/Http/Controllers/Api/Platform/Organizations/Provider/FundProviderController.php, app/Models/Implementation.php, app/Policies/FundPolicy.php
https://github.com/teamforus/forus/issues/1095
https://github.com/teamforus/forus/issues/1096
=> Added option to apply/accept paused funds

app/Http/Resources/FundRequestRecordResource.php, app/Http/Resources/Provider/ProviderVoucherResource.php, app/Http/Resources/Provider/ProviderVoucherTransactionResource.php, app/Http/Resources/Sponsor/SponsorVoucherTransactionResource.php, app/Http/Resources/VoucherResource.php, app/Http/Resources/VoucherTransactionNoteResource.php, app/Http/Resources/VoucherTransactionResource.php
fixed time on transaction overview https://github.com/teamforus/forus/issues/1124
=> Release v0.4.1

app/Mail/Funds/FundStartedMail.php, app/Models/Fund.php, resources/lang/nl/mails/implementations/general/fund_started.php, resources/views/emails/funds/fund_started.blade.php
https://github.com/teamforus/forus/issues/1058
=> Add fund started email

app/Models/Voucher.php
https://github.com/teamforus/forus/issues/1181
=> Don't export unassigned qr codes which need confirmation

app/Http/Controllers/Api/Platform/Organizations/FundsController.php, app/Http/Requests/Api/Platform/Organizations/Funds/StoreFundRequest.php, app/Http/Requests/Api/Platform/Organizations/Funds/UpdateFundRequest.php, app/Http/Resources/FundResource.php, app/Models/Fund.php, database/migrations/2019_11_28_203736_add_description_to_fund_table.php
https://github.com/teamforus/forus/issues/1176
=> Feature add fund description

app/Http/Controllers/Api/Platform/Organizations/Sponsor/VouchersController.php
https://github.com/teamforus/forus/issues/1214
=> Voucher export: add amount, expire_at, note, created_at to csv in .zip

config/forus/features/webshop.php
https://github.com/teamforus/forus/issues/1191
=> Remove settings to show some blocks on webshops

app/Http/Requests/Api/Platform/Organizations/Funds/StoreFundRequest.php, app/Http/Requests/Api/Platform/Organizations/Funds/UpdateFundRequest.php
https://github.com/teamforus/forus/issues/1230#event-2841571493
=> Fund description, allow just 140 characters

app/Http/Resources/FundProviderResource.php
https://github.com/teamforus/forus/issues/1220
=> Add validators information to fund providers call

app/Http/Controllers/Api/Platform/FundsController.php, app/Http/Controllers/Api/Platform/Organizations/Provider/FundProviderController.php, app/Http/Requests/Api/Platform/Funds/IndexFundsRequest.php, app/Http/Resources/FundResource.php, app/Http/Resources/OrganizationResource.php, app/Models/Fund.php, app/Models/Organization.php, app/Models/Tag.php, app/Models/Traits/HasTags.php, app/Providers/AppServiceProvider.php, app/Services/FileService/FileServiceProvider.php, app/Services/FileService/Traits/HasFiles.php, app/Services/MediaService/MediaService.php, app/Services/MediaService/MediaServiceProvider.php, app/Services/MediaService/Traits/HasMedia.php, database/migrations/2019_11_16_191116_create_tags_table.php, database/migrations/2019_11_21_160933_create_taggables_table.php, database/migrations/2019_11_21_201004_update_morphable_types.php
changelog 
- fund labels: tags, taggables,
=> Release v0.5.1

app/Policies/VoucherPolicy.php, resources/lang/nl/validation.php
https://github.com/teamforus/forus/issues/1224
=> Voucher validation, translation adjustments

app/Http/Controllers/Api/Platform/VouchersController.php, app/Models/Voucher.php, app/Policies/ProductPolicy.php, app/Policies/VoucherPolicy.php
https://github.com/teamforus/forus/issues/1183
=> Dont allow expired budget vouchers usage for product reservation

app/Http/Controllers/Api/Platform/VouchersController.php, app/Policies/VoucherPolicy.php
https://github.com/teamforus/forus/issues/1184
=> Don't allow sending emails and sharing for expired vouchers

app/Http/Resources/ProductResource.php, app/Models/Product.php
https://github.com/teamforus/forus/issues/1186
=> Product resource, don't return closed funds

app/Http/Requests/Api/Platform/Organizations/Transactions/IndexTransactionsRequest.php, app/Models/VoucherTransaction.php
https://github.com/teamforus/forus/issues/1189
=> Add parameter to filter transactions by active/closed fund

app/Http/Controllers/Api/Platform/NotificationsController.php, app/Http/Controllers/Api/Platform/Organizations/Funds/FundProviderController.php, app/Http/Requests/Api/Platform/Notifications/UpdateNotificationPreferencesRequest.php, app/Listeners/EmployeeSubscriber.php, app/Listeners/VoucherSubscriber.php, app/Models/VoucherTransaction.php, app/Services/Forus/Notification/Interfaces/INotificationRepo.php, app/Services/Forus/Notification/Models/NotificationPreference.php, app/Services/Forus/Notification/NotificationService.php, app/Services/Forus/Notification/Repositories/NotificationRepo.php, database/migrations/2019_12_01_202318_add_notification_type_to_notification_preferences.php
https://github.com/teamforus/forus/issues/755
=> Add option to unsubscribe from push notifications

app/Http/Resources/Sponsor/SponsorVoucherResource.php, app/Models/Voucher.php
https://github.com/teamforus/forus/issues/1278
=> Sponsor voucher resource, add property for record email

app/Policies/VoucherPolicy.php
removed trans as string is passed to deny function
teamforus/forus#1316
=> fix teamforus/forus#1316

resources/views/emails/funds/fund-requests/fund_request-created.blade.php
fixes variable not handled correctly in fund request blade
=> fix fund request created exception

app/Http/Controllers/Api/Platform/ProductsController.php
https://github.com/teamforus/forus/issues/1274
=> Use product filtration by fund on product samples

app/Http/Resources/FundProviderResource.php
https://github.com/teamforus/forus/issues/1319
=> Fund provider resource, add allow_some_products property

app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationRequest.php
https://github.com/teamforus/forus/issues/1328
=> Organization update, unique kvk rule ignore if kvk stays the same

app/Models/FundProvider.php, app/Services/Forus/Record/Repositories/RecordRepo.php, database/migrations/2019_12_01_202318_add_notification_type_to_notification_preferences.php, database/seeds/Lorem/LoremDbSeeder.php
https://github.com/teamforus/forus/issues/1332
=> fix migration and update fund-providers export states

resources/lang/nl/mails/implementations/general/balance_warning.php, resources/views/emails/funds/balance_warning.blade.php
https://github.com/teamforus/development/issues/256
=> Remove topup mail details in balance warning email

app/Http/Resources/OrganizationBasicResource.php, app/Http/Resources/OrganizationWithPrivateResource.php, app/Http/Resources/VoucherResource.php
https://github.com/teamforus/forus/issues/1283
=> Add organization resource with private data, use it on voucher data

app/Http/Controllers/Api/Platform/FundProviderInvitationsController.php, app/Http/Controllers/Api/Platform/Organizations/FundProviderInvitationsController.php, app/Http/Requests/Api/Platform/Organizations/FundProviderInvitations/IndexFundProviderInvitationRequest.php, app/Http/Requests/Api/Platform/Organizations/FundProviderInvitations/UpdateFundProviderInvitationRequest.php, app/Http/Resources/FundProviderInvitationResource.php, app/Http/Resources/OrganizationWithPrivateResource.php, app/Http/Resources/VoucherResource.php, app/Models/Organization.php, app/Policies/FundProviderInvitationPolicy.php, resources/lang/nl/push.php, routes/api-platform.php
Fund provider invitation policy
endpoint to get invitation list
to be expected:
show private organisation details on voucher card
=> Release v0.6.1

app/Http/Resources/FundProviderResource.php, app/Http/Resources/OrganizationBasicWithPrivateResource.php, app/Http/Resources/OrganizationWithPrivateResource.php, app/Http/Resources/VoucherResource.php
https://github.com/teamforus/forus/issues/1286
https://github.com/teamforus/forus/issues/1329
=> Add an organization resource with private data, use it on fund providers

app/Models/Product.php
https://github.com/teamforus/forus/issues/1351
=> Product list endpoint, allow search by organization name

app/Http/Controllers/Api/Platform/OrganizationsController.php, app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationBusinessTypeRequest.php, routes/api-platform.php
https://github.com/teamforus/forus/issues/1203
=> Platform, add endpoint to allow organization business type update only

app/Models/Implementation.php
https://github.com/teamforus/forus/issues/1063
=> Platform config response, add implementation name

app/Http/Resources/FundResource.php
https://github.com/teamforus/forus/issues/1363
=> Fund resource, return actual requester count on closed funds

app/Http/Controllers/Api/Platform/Organizations/Provider/FundProviderController.php, app/Services/Forus/Notification/NotificationService.php, resources/views/emails/base.blade.php
https://github.com/teamforus/forus/issues/1392
=> Provider applied email, send to admins as well

app/Http/Requests/Api/Platform/Organizations/StoreOrganizationRequest.php, app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationRequest.php
https://github.com/teamforus/forus/issues/1177
=> Allow duplicate kvk numbers for organizations on debug mode

app/Listeners/FundRequestSubscriber.php
Don't send fund-request mails when auto validation is on . 
https://github.com/teamforus/forus/issues/1394
=> do not send 'fund requested' emails to users on auto validated funds

app/Http/Requests/Api/Platform/Organizations/Vouchers/StoreVoucherRequest.php
https://github.com/teamforus/forus/issues/1382
=> Voucher creation, update amount error message

app/Http/Controllers/Api/Platform/Organizations/FundRequestsController.php, app/Models/FundRequest.php
https://github.com/teamforus/forus/issues/1397
=> Fund requests export, add created_at date

app/Models/VoucherTransaction.php
https://github.com/teamforus/forus/issues/1411
=> Voucher transactions, fix filtration by date

app/Http/Requests/Api/Platform/Organizations/Vouchers/IndexVouchersRequest.php, app/Models/Voucher.php
https://github.com/teamforus/forus/issues/1402
=> Vouchers search, add order by given query parameters

app/Listeners/VoucherSubscriber.php, app/Mail/Vouchers/AssignedVoucherMail.php, app/Models/Voucher.php, app/Services/Forus/Notification/NotificationService.php, resources/lang/nl/mails/implementations/general/voucher_assigned.php, resources/views/emails/vouchers/voucher_assigned.blade.php
https://github.com/teamforus/forus/issues/1356
=> Add email for voucher assignment

app/Http/Controllers/Api/Platform/Organizations/Sponsor/TransactionsController.php, app/Http/Requests/Api/Platform/Organizations/Transactions/IndexTransactionsRequest.php
https://github.com/teamforus/forus/issues/694
=> Transactions index request, adjust pagination limit

app/Http/Controllers/Api/Platform/Organizations/FundRequestsController.php, app/Models/Organization.php, app/Policies/FundRequestPolicy.php
https://github.com/teamforus/forus/issues/1412
=> Fix fund request policy

resources/views/emails/vouchers/share_product.blade.php
https://github.com/teamforus/forus/issues/1416
=> Share voucher with provider email, fix image embedding

app/Listeners/VoucherSubscriber.php, app/Mail/Vouchers/ProductReservedMail.php, app/Mail/Vouchers/ProductReservedUserMail.php, app/Services/Forus/Notification/NotificationService.php, resources/lang/nl/mails/implementations/general/product_reserved.php, resources/views/emails/funds/product_reserved.blade.php
https://github.com/teamforus/forus/issues/1415
=> Product voucher assignment, add new email for citizens

app/Http/Resources/PrevalidationResource.php
As some sponsor would like to see these records we don't need to filter them out anymore.
=> Show Eligible keys on prevalidation table

app/Http/Requests/Api/Platform/Organizations/Funds/UpdateFundRequest.php
remove product categories from fund update validation rules
required with this pr https://github.com/teamforus/forus-frontend/pull/1035
=> update fund validation rules

resources/views/pages/auth/deep_link.blade.php, resources/views/pages/layout.blade.php
https://github.com/teamforus/forus/issues/1426
=> Change 'Open me app' button styles

app/Models/Voucher.php, app/Services/Forus/Record/Repositories/Interfaces/IRecordRepo.php, app/Services/Forus/Record/Repositories/RecordRepo.php
https://github.com/teamforus/forus/issues/1436
=> Vouchers search by assigned email

resources/views/pages/auth/deep_link.blade.php, resources/views/pages/layout.blade.php
https://github.com/teamforus/forus/issues/1426
=> Open me app button adjustment

app/Media/OrganizationLogoMediaConfig.php
https://github.com/teamforus/forus/issues/588
=> Organization logo, change aspect ratio

app/Http/Requests/Api/Platform/Organizations/StoreOrganizationRequest.php, app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationRequest.php, app/Listeners/OrganizationSubscriber.php, app/Models/Organization.php, app/Rules/Base/KvkRule.php, app/Services/KvkApiService/KvkApi.php
https://github.com/teamforus/forus/issues/1446
=> kvk workaround

app/Http/Resources/VoucherResource.php, app/Models/Voucher.php
https://github.com/teamforus/forus/issues/1422
=> Voucher resource, add last active day field

app/Http/Resources/FundResource.php, app/Http/Resources/ImplementationResource.php
https://github.com/teamforus/forus/issues/1424
=> Fund resource, add details about fund implementation

app/Models/Fund.php
https://github.com/teamforus/forus/issues/1333
=> use 'validate_records' role instead of 'validator' role to check records validity

app/Mail/User/IdentityEmailVerificationMail.php, app/Services/Forus/Identity/Models/IdentityEmail.php, app/Services/Forus/Notification/NotificationService.php
https://github.com/teamforus/forus/issues/1465
=> Fix verify secondary email exception

app/Listeners/FundSubscriber.php, app/Models/Implementation.php
https://github.com/teamforus/forus/issues/1470
=> Fix fund creation email exception

app/Http/Controllers/Api/IdentityController.php
https://github.com/teamforus/forus/issues/1463
=> Login email, platform information

app/Http/Resources/FundCriterionResource.php
https://github.com/teamforus/forus/issues/1471
=> Fund criteria resource, add description_html field

app/Http/Requests/Api/Platform/Funds/Requests/StoreFundRequestRequest.php
https://github.com/teamforus/forus/issues/1473
=> Fund request validation, messages adjustment

app/Http/Requests/Api/Platform/Organizations/Funds/StoreFundRequest.php, app/Http/Requests/Api/Platform/Organizations/Funds/UpdateFundRequest.php, database/migrations/2020_04_15_205801_update_fund_criteria_value_field.php
https://github.com/teamforus/forus/issues/1479
=> Fund criteria, increase value character limit

app/Http/Controllers/Api/IdentityFallbackController.php
https://github.com/teamforus/forus/issues/1489
=> Identity store fallback endpoint, add confirmation parameter

app/Http/Resources/FundProviderResource.php
https://github.com/teamforus/forus/issues/1488
=> Fund providers resource, add employees information

app/Models/VoucherTransaction.php, resources/lang/nl/export.php
https://github.com/teamforus/forus/issues/1500
=> Transactions export CSV, add transaction id

app/Http/Resources/FundResource.php
https://github.com/teamforus/forus/issues/1517
=> Fund resource, add provider organizations count

app/Http/Controllers/Api/Platform/Organizations/FundsController.php, app/Models/Fund.php
https://github.com/teamforus/forus/issues/1513
=> Platform funds list, sort by state (active funds first)

app/Http/Resources/FundResource.php
https://github.com/teamforus/forus/issues/1519
=> Fund resource, 'csv_required_keys' field explicit conversion to array

app/Http/Resources/FundProviderResource.php
https://github.com/teamforus/forus/issues/1520
=> Fund provider resource, add IBAN property

app/Http/Controllers/Api/Platform/Organizations/Funds/FundProviderController.php, app/Models/FundProvider.php, app/Scopes/Builders/FundProviderQuery.php
https://github.com/teamforus/forus/issues/1525
=> Fund providers endpoint, sort by highest earners

app/Http/Controllers/Api/IdentityFallbackController.php
https://github.com/teamforus/forus/issues/1536
=> fix mobile sign-in link on desktop when fallback enabled

app/Http/Controllers/Api/StatusController.php, routes/api.php
https://github.com/teamforus/forus/issues/1444
=> endpoint to check api availability

app/Http/Requests/Api/Platform/Organizations/Funds/FinanceRequest.php, app/Models/FundProvider.php
https://github.com/teamforus/forus/issues/1526
=> Fund provider finances statistics, add filtration by year

app/Mail/Funds/FundBalanceWarningMail.php, app/Models/Fund.php, app/Services/Forus/Notification/NotificationService.php
https://github.com/teamforus/forus/issues/1549
=> Remove bunq top up code from the fund balance check

app/Http/Controllers/Api/Platform/Organizations/Funds/FundProviderController.php
https://github.com/teamforus/forus/issues/1565
=> Disable products on fund provider dismiss

app/Models/Prevalidation.php, resources/lang/nl/export.php
https://github.com/teamforus/forus/issues/1604
=> Prevalidations export, add a state field

app/Http/Controllers/Api/Platform/Organizations/Provider/FundProviderController.php, app/Http/Requests/Api/Platform/Funds/IndexFundsRequest.php
https://github.com/teamforus/forus/issues/1597
=> Fund provider available funds endpoint, add pagination

app/Http/Controllers/Api/Identity/RecordController.php, app/Http/Requests/Api/Records/IndexRecordsRequest.php, app/Http/Requests/Api/Records/RecordStoreRequest.php, app/Models/Implementation.php, app/Services/Forus/Record/Models/Record.php, app/Services/Forus/Record/Repositories/Interfaces/IRecordRepo.php, app/Services/Forus/Record/Repositories/RecordRepo.php
Endpoint filter required for me-app archived records screen
=> Develop.fetch deleted records

app/Models/Implementation.php
=> fix collection namespace

resources/lang/nl/mails/implementations/general/identity_email_verification.php, resources/views/emails/identity-email-verification.blade.php
https://github.com/teamforus/forus/issues/1578
=> Identity verification email, add link

app/Http/Resources/ProductResource.php
https://github.com/teamforus/forus/issues/1547
=> Product resource, return old price as 'null' if it's value isn't set

app/Http/Controllers/Api/Platform/Organizations/ImplementationsController.php, app/Http/Requests/Api/Platform/Organizations/Implementations/UpdateImplementationCmsRequest.php, app/Http/Requests/Api/Platform/Organizations/Implementations/UpdateImplementationDigiDRequest.php, app/Http/Requests/Api/Platform/Organizations/Implementations/UpdateImplementationEmailRequest.php, app/Http/Resources/ImplementationPrivateResource.php, app/Policies/ImplementationPolicy.php, app/Scopes/Builders/OrganizationQuery.php, database/seeds/PermissionsTableSeeder.php, database/seeds/RolePermissionsTableSeeder.php, database/seeds/RolesTableSeeder.php, routes/api-platform.php
https://github.com/teamforus/forus/issues/1612
=> Implementation management, update permissions

app/Http/Requests/Api/Platform/Organizations/StoreOrganizationRequest.php, app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationRequest.php
https://github.com/teamforus/forus/issues/1605
=> Organization validation, limit allowed organization name length

app/Mail/Auth/UserLoginMail.php
https://github.com/teamforus/forus/issues/1573
=> Login email, adjust translation

app/Models/FundProvider.php
https://github.com/teamforus/forus/issues/1621
=> Fund provider financial statistics, adjust calculations

app/Http/Controllers/Api/Platform/RolesController.php, app/Http/Resources/RoleResource.php, app/Models/Role.php, app/Models/RoleTranslation.php, database/migrations/2020_06_26_130948_add_role_translation_table.php, database/migrations/2020_07_03_142556_drop_name_field_from_roles_table.php, database/seeds/DatabaseSeeder.php, database/seeds/RoleTranslationTableSeeder.php
https://github.com/teamforus/forus/issues/1570
=> Add role translations

resources/lang/nl/notifications/notifications_fund_providers.php
Revoked products is still unclear. Placed a comment in the issue.
=> Checked the text and placed update.

app/Services/Forus/Notification/NotificationService.php
https://github.com/teamforus/forus/issues/1658
=> Login email, update notification preferences link

app/Digests/ProviderFundsDigest.php
=> Remove %s as its not needed

app/Models/Fund.php, resources/views/pages/auth/deep_link.blade.php, resources/views/pages/layout.blade.php
=> disable cache on desktop deep-link page and fix product vouchers generator

app/Http/Resources/FundResource.php
https://github.com/teamforus/forus-backend/commit/36e88e3c779eb70a6af4a7d6455ff6bc6dc87290
=> Fix typo from branch merge

app/Digests/SponsorDigest.php, app/Digests/ValidatorDigest.php, app/Mail/Digest/DigestProviderFundsMail.php, app/Mail/Digest/DigestProviderProductsMail.php, app/Mail/Digest/DigestRequesterMail.php, app/Mail/Digest/DigestSponsorMail.php, app/Mail/Digest/DigestValidatorMail.php, app/Models/Fund.php, resources/lang/nl/digests/provider_funds.php, resources/lang/nl/digests/provider_products.php, resources/lang/nl/digests/requester.php, resources/lang/nl/digests/sponsor.php, resources/lang/nl/digests/validator.php, resources/views/pages/auth/deep_link.blade.php, resources/views/pages/layout.blade.php
Changelog:
- Disable cache on deep-link page
- fix product voucher generator product_id and amount fields, not returnable https://github.com/teamforus/forus/issues/1674
- digest fixes: teamforus/forus#1657, teamforus/forus#1664, teamforus/forus#1676, teamforus/forus#1677, teamforus/forus#1687
- fix sponsor digest dashboard url
=> Release v0.13.1

app/Http/Requests/Api/Platform/Organizations/Funds/StoreFundRequest.php, app/Http/Requests/Api/Platform/Organizations/Funds/UpdateFundCriteriaRequest.php, app/Http/Resources/FundCriterionResource.php, app/Models/Fund.php, app/Models/FundCriterion.php, database/migrations/2020_08_02_183756_add_title_field_to_fund_criteria_table.php
https://github.com/teamforus/forus/issues/1685
=> Fund criteria, add title field

resources/views/emails/identity-email-verification.blade.php
https://github.com/teamforus/forus/issues/1697
=> Identity email verification fix

app/Http/Controllers/Api/Platform/OrganizationsController.php, app/Http/Requests/Api/Platform/Organizations/StoreOrganizationRequest.php, app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationRequest.php, app/Http/Resources/OrganizationResource.php, app/Http/Resources/ProviderResource.php, app/Models/Organization.php, database/migrations/2020_08_01_194516_add_description_field_to_organizations_table.php
https://github.com/teamforus/forus/issues/1650
=> Add organization description field

app/Http/Requests/Api/Platform/Funds/Requests/IndexFundRequestsRequest.php, app/Models/FundRequest.php
https://github.com/teamforus/forus/issues/1702
=> Validator fund requests endpoint, add search and sort parameters

app/Http/Controllers/Api/Identity/IdentityEmailsController.php, app/Http/Requests/Api/Identity/Emails/StoreIdentityEmailRequest.php, app/Http/Requests/Api/Identity/IdentityEmailStoreRequest.php, app/Rules/IdentityEmailUniqueRule.php
https://github.com/teamforus/forus/issues/1750
=> Identity email store endpoint, add unique email validation

app/Mail/Funds/FundRequests/FundRequestCreatedMail.php, app/Notifications/Identities/FundRequest/IdentityFundRequestCreatedNotification.php, resources/lang/nl/mails/implementations/general/fund_request_created.php, resources/views/emails/funds/fund-requests/fund_request-created.blade.php
https://github.com/teamforus/forus/issues/1791
=> Fund request created email, adjustments

resources/lang/nl/mails/implementations/general/fund_request_clarification_requested.php, resources/views/emails/funds/fund-request-clarifications/fund_request-clarification-requested.blade.php
https://github.com/teamforus/forus/issues/1789
=> Fund request clarification mail adjustments

app/Http/Resources/VoucherResource.php
To show markdown on new product description block on voucher page. https://github.com/teamforus/forus-frontend/pull/1419
=> Added description_html of product to voucher resource

app/Http/Requests/Api/Platform/Funds/Requests/StoreFundRequestRequest.php
https://github.com/teamforus/forus/issues/1802
=> Fund request validation, require criteria message fix

app/Services/EventLogService/EventLogService.php, resources/lang/nl/notifications/notifications_fund_providers.php
https://github.com/teamforus/forus/issues/1838
=> Fund expiring notification, display the actual dates

app/Http/Controllers/Api/Platform/FundsController.php, app/Http/Controllers/Api/Platform/ProductsController.php, app/Listeners/VoucherSubscriber.php, app/Models/Fund.php, app/Models/Voucher.php, app/Policies/FundPolicy.php, app/Policies/VoucherPolicy.php, app/Services/KvkApiService/KvkApi.php, app/Services/KvkApiService/KvkApiServiceProvider.php, database/migrations/2020_10_21_215713_add_show_on_webshop_field_to_products_table.php, resources/lang/nl/validation.php, resources/views/emails/vouchers/voucher_assigned_product.blade.php
- E-mail assigned when requesting funds with product formula  https://github.com/teamforus/forus/issues/1858
- Add field to to product to not show it on webshop https://github.com/teamforus/forus/issues/1855
- Remove product description from assign product mail  https://github.com/teamforus/forus/issues/1854 -> reason product description contain markdown
- Product soldout while still in stock https://github.com/teamforus/forus/issues/1852
- https://github.com/teamforus/forus/issues/1759
=> #1759, #1852, #1854, #1855 and #1858

app/Http/Controllers/Api/Platform/Vouchers/PhysicalCardRequestsController.php, app/Mail/Vouchers/RequestPhysicalCardMail.php, app/Services/Forus/Notification/NotificationService.php, resources/lang/nl/mails/implementations/general/request_physical_card.php, resources/views/emails/vouchers/request-physical-card.blade.php
https://github.com/teamforus/forus/issues/1860
=> Implement physical card requested email

app/Http/Requests/Api/Platform/Organizations/IndexOrganizationRequest.php, app/Models/Organization.php
https://github.com/teamforus/forus/issues/1868
=> Organizations endpoint, add fund_type parameter

config/forus/funds.php
https://github.com/teamforus/forus/issues/1867
=> Store voucher request, increase max sponsor voucher amount

config/file.php, resources/lang/nl/validation.php
https://github.com/teamforus/forus/issues/1865
=> Increase file upload size limit

app/Http/Resources/FundRequestClarificationResource.php, app/Models/FundRequestRecord.php, app/Models/Product.php
https://github.com/teamforus/forus/issues/1718
=> Fund request clarification resource, add fund request record name

app/Http/Requests/Api/Platform/Organizations/Products/StoreProductRequest.php, app/Http/Requests/Api/Platform/Organizations/Products/UpdateProductRequest.php, database/migrations/2020_12_06_045410_update_product_description_field.php
https://github.com/teamforus/forus/issues/1943
=> Product description limit increase

app/Http/Requests/Api/Platform/Organizations/Products/UpdateProductRequest.php
https://github.com/teamforus/forus/issues/1939
=> Update product request, no_price_type rule adjustment

app/Http/Requests/Api/Platform/Organizations/Products/StoreProductRequest.php, app/Http/Requests/Api/Platform/Organizations/Products/UpdateProductRequest.php, app/Http/Resources/VoucherCollectionResource.php, app/Http/Resources/VoucherResource.php, app/Models/Voucher.php, database/migrations/2020_12_06_045410_update_product_description_field.php, resources/lang/nl/mails/implementations/general/voucher_sent.php
Changelog:
Product description increase to 2500 characters
Add used / last transaction date to vouchers resource
bug fix product creation
=> Release v0.17.1

app/Mail/Vouchers/ProductReservedMail.php, app/Notifications/Identities/Voucher/IdentityProductVoucherReservedNotification.php, app/Notifications/Organizations/Products/ProductReservedNotification.php, resources/views/emails/funds/product_bought.blade.php
https://github.com/teamforus/forus/issues/1877
=> Add back e-mail about product reservation which is sent to provider

app/Http/Controllers/Api/Platform/VouchersController.php
https://github.com/teamforus/forus/issues/1984
=> Platform vouchers endpoint, sort newest vouchers on top

app/Http/Controllers/Api/Platform/Vouchers/PhysicalCardRequestsController.php, resources/views/emails/vouchers/request-physical-card.blade.php
https://github.com/teamforus/forus/issues/1978
=> Physical card request emai, add house addition information

app/Http/Resources/Validator/ValidatorFundRequestRecordResource.php, app/Http/Resources/Validator/ValidatorFundRequestResource.php
https://github.com/teamforus/forus/issues/1977
=> Validator fund request resource, add note field

app/Http/Requests/Api/Platform/Funds/Requests/IndexFundRequestsRequest.php, app/Models/FundRequest.php
https://github.com/teamforus/forus/issues/2045
https://github.com/teamforus/forus/issues/2046
=> update fund request sort_by filter

app/Http/Requests/Api/Platform/Organizations/StoreOrganizationRequest.php, app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationRequest.php
https://github.com/teamforus/forus/issues/2037
=> Organization phone validation, allow shorter length

app/Digests/SponsorDigest.php
https://github.com/teamforus/forus/issues/2005
=> sponsor digest disable texts about the lack of new providers

app/Http/Controllers/DigIdController.php
https://github.com/teamforus/forus/issues/1937
=> update digid cancel page redirect

app/Console/Commands/SendAllDigestsCommand.php, app/Console/Kernel.php
https://github.com/teamforus/forus/issues/2043
=> Disable requester digest

app/Scopes/Builders/VoucherQuery.php
show non-returnable vochers in product voucher generator (created by users)
=> Hotfix: product voucher generator changed visibility to sponsor

app/Http/Requests/Api/Platform/Organizations/Vouchers/IndexVouchersRequest.php, app/Models/Voucher.php
https://github.com/teamforus/forus/issues/2058
=> Voucher resource, add in_use filter

app/Http/Resources/ProductResource.php
https://github.com/teamforus/forus/issues/2056
=> Product resource add fund expiration date fields

app/Http/Controllers/Api/Platform/Organizations/ImplementationsController.php, app/Http/Requests/Api/Platform/Organizations/Implementations/UpdateImplementationCmsRequest.php, app/Http/Resources/ImplementationPrivateResource.php, app/Models/Implementation.php, database/migrations/2021_01_05_222659_add_description_provider_field_to_implementations_table.php, database/migrations/2021_01_05_222659_add_description_providers_field_to_implementations_table.php
https://github.com/teamforus/forus/issues/1965
=> Implementation add provider description field

app/Models/VoucherTransaction.php, resources/lang/nl/push.php
https://github.com/teamforus/forus/issues/2063
=> Subsidy transaction push notification change texts

app/Scopes/Builders/VoucherQuery.php
https://github.com/teamforus/forus/issues/2061
=> search voucher in generator by code uid

resources/lang/nl/mails/implementations/general/email_activation.php
https://github.com/teamforus/forus/issues/2078
=> fix me_app sign-up email text

app/Http/Resources/Validator/ValidatorFundRequestRecordResource.php, app/Http/Resources/Validator/ValidatorFundRequestResource.php, app/Models/FundRequest.php, config/forus/seeders/lorem_db_seeder.php, database/seeds/Lorem/LoremDbSeeder.php
We should test the validation dashboard again after this update (permission and external validators)
https://github.com/teamforus/forus/issues/2084
=> improve fund-requests endpoint loading time

app/Http/Requests/Api/Platform/SearchProductsRequest.php, app/Http/Resources/ProductResource.php, app/Models/Product.php, app/Scopes/Builders/ProductQuery.php
https://github.com/teamforus/forus/issues/1850
=> sort products and actions by price/min_price

app/Mail/Vouchers/SubsidyPaymentSuccessMail.php, resources/lang/nl/mails/implementations/general/subsidy_payment_success.php, resources/views/emails/vouchers/subsidy_payment_success.blade.php
https://github.com/teamforus/forus/issues/2103
=> Subsidy voucher transaction email, make product name bold

app/Services/Forus/Record/Repositories/RecordRepo.php, resources/lang/nl/record.php
https://github.com/teamforus/forus/issues/2090
=> Add validation error for: 'record.exceptions.cant_delete_primary_email

app/Listeners/VoucherSubscriber.php, app/Models/Implementation.php, app/Notifications/Identities/Voucher/IdentityVoucherAddedBudgetNotification.php, app/Notifications/Identities/Voucher/IdentityVoucherAddedNotification.php, app/Notifications/Identities/Voucher/IdentityVoucherAddedSubsidyNotification.php, app/Notifications/Identities/Voucher/IdentityVoucherAssignedBudgetNotification.php, app/Notifications/Identities/Voucher/IdentityVoucherAssignedNotification.php, app/Notifications/Identities/Voucher/IdentityVoucherAssignedSubsidyNotification.php, database/migrations/2021_02_12_105150_migrate_subsidy_fund_voucher_notifications.php, resources/lang/nl/mails/implementations/general/payment_success.php, resources/lang/nl/mails/implementations/general/subsidy_payment_success.php, resources/lang/nl/notifications/notifications_identities.php, resources/lang/nl/push.php
@aghimpu could you help me create seperate notifications for subsidy vouchers (added / created)
same as here but now for normal notifications / event logs https://github.com/teamforus/forus-backend/pull/1009
=> added some texts WIP

app/Listeners/EmployeeSubscriber.php, resources/lang/nl/notifications/notifications_identities.php
https://github.com/teamforus/forus/issues/2117
=> Employee update notification, fix translation

app/Http/Resources/ProductResource.php, app/Models/Product.php, app/Scopes/Builders/ProductQuery.php, config/forus/clients.php, config/forus/features/dashboard.php, config/forus/features/webshop.php, routes/api-platform.php
Changelog:
Enable transactions list and fix products list min and max price
=> Release v0.20.1

app/Mail/Funds/FundClosed.php, app/Mail/Funds/FundRequestClarifications/FundRequestClarificationRequestedMail.php, app/Mail/Funds/FundRequests/FundRequestApprovedMail.php, app/Mail/Funds/FundRequests/FundRequestResolvedMail.php, app/Mail/Vouchers/AssignedVoucherMail.php, app/Mail/Vouchers/SendVoucherMail.php, resources/lang/nl/mails/implementations/general/email_activation.php, resources/lang/nl/mails/implementations/general/fund_closed.php, resources/lang/nl/mails/implementations/general/fund_expires.php, resources/lang/nl/mails/implementations/general/fund_request_approved.php, resources/lang/nl/mails/implementations/general/fund_request_clarification_requested.php, resources/lang/nl/mails/implementations/general/fund_request_created.php, resources/lang/nl/mails/implementations/general/fund_request_resolved.php, resources/lang/nl/mails/implementations/general/identity_email_verification.php, resources/lang/nl/mails/implementations/general/request_physical_card.php, resources/lang/nl/mails/implementations/general/voucher_assigned_subsidy.php, resources/lang/nl/mails/implementations/general/voucher_sent.php, resources/views/emails/funds/fund-request-clarifications/fund_request-clarification-requested.blade.php, resources/views/emails/funds/fund-request-records/fund_request-declined.blade.php, resources/views/emails/funds/fund-requests/fund_request-approved.blade.php, resources/views/emails/funds/fund-requests/fund_request-created.blade.php, resources/views/emails/funds/fund-requests/fund_request-denied.blade.php, resources/views/emails/funds/fund-requests/fund_request-resolved.blade.php, resources/views/emails/funds/fund_closed.blade.php, resources/views/emails/funds/fund_expires.blade.php, resources/views/emails/identity-email-verification.blade.php, resources/views/emails/user/email_activation.blade.php, resources/views/emails/vouchers/voucher_assigned_subsidy.blade.php, resources/views/emails/vouchers/voucher_sent.blade.php
we could not test voucher expires soon and fund closed e-mails
=> Added informal texts for CMS e-mails

app/Http/Controllers/Api/Platform/Organizations/FundsController.php, app/Http/Resources/FundResource.php, app/Scopes/Builders/VoucherQuery.php
https://github.com/teamforus/forus/issues/2126
=> Organization fund statistics, exclude inactive and expired vouchers

app/Http/Requests/Api/Platform/Funds/Requests/StoreFundRequestRequest.php, app/Rules/IdentityEmailUniqueRule.php, resources/lang/en/validation.php, resources/lang/nl/validation.php
https://github.com/teamforus/forus/issues/2143
https://github.com/teamforus/forus/issues/2140
=> Text fix.fund request request

resources/views/messages/__minimal.blade.php, resources/views/messages/email-verified.blade.php
https://github.com/teamforus/forus/issues/2145
=> Email verified page enhancements

app/Models/FundProviderInvitation.php
https://github.com/teamforus/forus/issues/2154
=> Fund provider invitation fix

app/Providers/RouteServiceProvider.php
https://github.com/teamforus/forus/issues/2146
=> physical card not found message

.env.example, app/Services/BunqService/BunqService.php, app/Services/BunqService/Commands/ProcessBunqPaymentsCommand.php, app/Services/BunqService/Commands/ProcessBunqTopUpsCommand.php, app/Services/Forus/Notification/EmailFrom.php, app/helpers.php, config/bunq.php
https://github.com/teamforus/forus/issues/2157
=> bunq iban skip list

app/Http/Controllers/DigIdController.php, app/Http/Resources/FundResource.php, app/Models/FundConfig.php, app/Models/FundProviderProduct.php, app/Services/DigIdService/DigIdServiceProvider.php, app/Services/DigIdService/Models/DigIdSession.php, database/migrations/2021_03_18_093632_add_allow_direct_requests_to_fund_configs_table.php
https://github.com/teamforus/forus/issues/2108
https://github.com/teamforus/forus/issues/2251
=> digid cancel message, funds direct request flag

app/Http/Resources/ImplementationPrivateResource.php
https://github.com/teamforus/forus/issues/2265
=> fix communication type dropdown

app/Http/Controllers/Api/Platform/Organizations/Sponsor/ProvidersController.php
https://github.com/teamforus/forus/issues/2039
=> Add export type request parameter for provider list export endpoint

app/Http/Requests/Api/Platform/Vouchers/PhysicalCards/StorePhysicalCardRequest.php
Changelog: 
allow physical card codes which start with 1002
=> Release v0.23.2

app/Models/FundProvider.php
Fix for bug with export
https://github.com/teamforus/itsm/issues/478
=> fix providers export

app/Listeners/FundRequestClarificationSubscriber.php
https://github.com/teamforus/forus/issues/2139
=> Fund request clarification notification, fix missing variables

app/Media/OrganizationLogoMediaConfig.php
https://github.com/teamforus/forus/issues/2133
=> Organization logo media, update aspect ratio

resources/views/emails/vouchers/voucher_assigned_budget.blade.php
Changelog:
fix for e-mail communication type missing
=> Release/v0.24.1: fix voucher assigned email title

app/Http/Controllers/Api/Platform/VouchersController.php, app/Http/Requests/Api/Platform/Vouchers/StoreProductVoucherRequest.php, app/Models/Voucher.php
https://github.com/teamforus/forus/issues/2291
=> update product voucher reservation expire date formula

app/Models/Voucher.php
https://github.com/teamforus/forus/issues/2277
=> activation_code_uid assign

app/Http/Resources/VoucherCollectionResource.php
https://github.com/teamforus/forus/issues/2301
=> fix amount on vouchers list

app/Http/Requests/Api/Platform/Vouchers/PhysicalCardRequests/StorePhysicalCardRequestRequest.php
https://github.com/teamforus/forus/issues/2299
=> Physical card request validation, house number validate as number

app/Http/Resources/Sponsor/SponsorVoucherResource.php, app/Models/Data/VoucherExportData.php, app/Models/Voucher.php
https://github.com/teamforus/itsm/issues/507
=> Vouchers, fix in_use status for vouchers with reservations

app/Http/Controllers/Api/Platform/Organizations/Funds/FundProviders/ProductsController.php, app/Http/Resources/Sponsor/SponsorProviderResource.php, app/Models/Organization.php
https://github.com/teamforus/forus/issues/2292#event-4831029651
=> Sponsor provider resource, products filtering fix

app/Http/Controllers/Api/Platform/Organizations/Funds/FundProviderController.php, app/Http/Controllers/Api/Platform/Organizations/Provider/FundProviderController.php, app/Http/Resources/FundProviderResource.php, app/Models/FundProvider.php, app/Policies/FundProviderPolicy.php, app/Scopes/Builders/FundProviderQuery.php, routes/api-platform.php
https://github.com/teamforus/forus/issues/2297
=> Fund provider, add endpoint for deleting fund application

app/Models/Fund.php
Changelog: 
restore previous funds sorting order
=> Release v0.27.1: restore previous funds sorting order

app/Models/Fund.php
https://github.com/teamforus/forus/issues/2327
=> restore previous funds sorting order

app/Http/Controllers/Api/Platform/Vouchers/PhysicalCardRequestsController.php, app/Http/Requests/Api/Platform/Vouchers/PhysicalCardRequests/StorePhysicalCardRequestRequest.php, app/Policies/VoucherPolicy.php, routes/api-platform.php
https://github.com/teamforus/forus/issues/2320
=> Physical card requests add validation endpoint

app/Exports/VoucherExport.php, app/Models/Data/VoucherExportData.php
https://github.com/teamforus/forus/issues/2342
=> Voucher data export, add 'in_use_date' field

app/Http/Controllers/Api/IdentityController.php, app/Models/Fund.php, app/Models/FundConfig.php, app/Services/BunqService/BunqService.php, database/migrations/2021_07_16_161222_remove_subtract_transaction_costs_from_fund_configs_table.php
https://github.com/teamforus/forus/issues/2295
=> remove substract transactions cost

app/Http/Controllers/Api/Platform/Organizations/Sponsor/ProvidersController.php, app/Http/Requests/Api/Platform/Organizations/Sponsor/Providers/IndexProvidersRequest.php, app/Models/FundProvider.php, app/Scopes/Builders/FundProviderQuery.php, app/Scopes/Builders/OrganizationQuery.php
https://github.com/teamforus/forus/issues/2361
=> Sponsor provider organization list, add sort parameter

resources/lang/nl/events/voucher.php
https://github.com/teamforus/forus/issues/2358
=> Voucher transaction events add missing translation

app/Mail/Funds/FundBalanceWarningMail.php, app/Models/Fund.php, app/Services/Forus/Notification/NotificationService.php, resources/lang/nl/mails/implementations/general/balance_warning.php, resources/views/emails/funds/balance_warning.blade.php
https://github.com/teamforus/forus/issues/2346
=> Balance warning email enhancements

app/Http/Requests/Api/Platform/Organizations/Vouchers/IndexVouchersRequest.php, app/Models/Voucher.php
https://github.com/teamforus/forus/issues/2359
=> Voucher search add option to filter by duplicate identity

resources/lang/nl/export.php
https://github.com/teamforus/itsm/issues/560
=> Voucher transaction export, add missing translation

app/Http/Resources/Validator/ValidatorFundRequestResource.php, app/Models/Fund.php, app/Models/FundRequest.php, app/Models/FundRequestClarification.php, app/Models/Voucher.php, database/migrations/2021_11_05_033928_add_resolved_at_field_to_fund_requests_table.php, resources/lang/nl/export.php
https://github.com/teamforus/MIW-2021-management-information-Waalwijk/issues/2
https://github.com/teamforus/MIW-2021-management-information-Waalwijk/issues/3
=> Validator fund request lead times

app/Http/Requests/Api/Platform/Organizations/Funds/StoreFundRequest.php, app/Http/Requests/Api/Platform/Organizations/Funds/UpdateFundRequest.php, database/migrations/2021_12_03_101553_update_fund_description_field.php
https://github.com/teamforus/EFO-2021-external-funds-overview-Nijmegen/issues/31
=> Fund description increase character limit

app/Http/Requests/Api/Platform/Organizations/Funds/StoreFundRequest.php, app/Http/Requests/Api/Platform/Organizations/Funds/UpdateFundRequest.php
https://github.com/teamforus/EFO-2021-external-funds-overview-Nijmegen/issues/34
=> Increase fund description short limit

app/Services/EventLogService/EventLogService.php, database/seeds/resources/mail_templates/notifications_identities/voucher_budget_transaction.md, database/seeds/resources/mail_templates/notifications_identities/voucher_budget_transaction_informal.md
https://github.com/teamforus/itsm/issues/620
=> Update budget voucher transaction email template

app/Models/FundConfig.php, app/Policies/VoucherPolicy.php, database/migrations/2022_01_17_193007_add_employee_can_see_product_vouchers_to_fund_configs_table.php
https://github.com/teamforus/itsm/issues/654
=> Product voucher details page fix authorization issue

app/Policies/FundRequestPolicy.php, resources/lang/nl/fund_requests.php, resources/lang/nl/policies/fund_requests.php
For the feature fund disregard we need some translation. I can't really figure out what scenario's need this translation. Can;t reproduce it easy so not sure what kind of translation I should use.
Also, the way I did it it's not working. IT shows me the variable of the translation instead of the translation itself. @maxvisser This is the last thing before we can stage the release. Could you maybe do thiss?
=> begin with adding translation

app/Http/Controllers/Api/Platform/SearchController.php, app/Http/Requests/Api/Platform/SearchRequest.php
https://github.com/teamforus/itsm/issues/723
=> generic seach endpoint, add 'with_external' query parameter

app/Http/Resources/FundResource.php, app/Models/Fund.php, app/Scopes/Builders/VoucherQuery.php
https://github.com/teamforus/itsm/issues/720
=> financial dashboard statistics endpoints add deactivated vouchers

.github/workflows/run_tests.yml
Added GitHub CI workflow for unit and feature tests.
- All php files, included in unit/feature directories will be executed
- You can run or re-run tests manually in Actions directory
- Trigger - any PR or any branch push
For PR creators - please, take a look at your tests results after PR creation
For PR reviewers - please, check that results are green (@GerbenBosschieter @dev-rminds)
=> GitHub CI workflow for unit and feature tests

composer.json, composer.lock, resources/views/pdf/vouchers_export.blade.php
Upgrade for left security alerts in Backend
**Note**
Before merging you can check migration guideline from 1.2 to 2.0
https://github.com/dompdf/dompdf/wiki/Migration-Guide
=> Upgrade dompdf

.github/workflows/run_tests.yml
Added all debug params to have more info ahead ( to prevent rerunning to get info )
=> phpunit debug

app/Models/Fund.php
https://github.com/teamforus/DevOps/issues/74
=> include the last day on fund expiration check

app/Http/Controllers/Api/Platform/Organizations/FundRequestsController.php, app/Http/Requests/Api/Platform/Funds/Requests/IndexFundRequestsRequest.php, app/Models/FundRequest.php, app/Searches/FundRequestSearch.php, database/seeders/LoremDbSeeder.php
Add fund requests sorting, refactor fund request search
=> Add fund requests sorting

resources/lang/nl/events/voucher.php
Related to:
https://github.com/teamforus/DevOps/issues/260
=> Develop.minor translation fixes 1

app/Http/Requests/Api/Platform/Reimbursements/StoreReimbursementRequest.php, database/migrations/2023_03_15_231931_update_reimbursement_description_field.php
make reimbursement description optional as requested in https://github.com/teamforus/forus-frontend/pull/2553
=> make reimbursement description field optional

.github/pull_request_template.md
Added template for Github PR which would be good to use for anyone who creates PRs here
**Reasoning** - not to forget/skip necessary steps for our pipeline. 
Would be really useful to hear feedback about the content of PR template from developers and devops team - what to add / what to remove
=> Added GitHub Pull-Request template

app/Traits/ThrottleWithMeta.php, resources/lang/nl/throttles/make_transaction.php
and prevent zero value for available_in time in throttle
=> Add translation for throttle transaction store

app/Http/Controllers/Api/Platform/FundsController.php, app/Http/Controllers/Api/Platform/Organizations/FundsController.php, app/Http/Controllers/Api/Platform/Organizations/Products/FundsController.php, app/Http/Controllers/Api/Platform/Organizations/Provider/FundProviderController.php, app/Http/Requests/Api/Platform/Funds/IndexFundsRequest.php, app/Http/Requests/Api/Platform/Organizations/Funds/IndexFundRequest.php, app/Searches/FundSearch.php
adds fund_ids filter to funds endpoint
=> add fund_ids filter to funds endpoint

app/Listeners/ProductSubscriber.php, app/Models/BusinessType.php, app/Models/Implementation.php, app/Models/Organization.php, app/Scopes/Builders/FundProviderQuery.php
There was some refactor in code, so QA need to check also list of providers on webshop
=> Send notification about new product added to all accepted funds

app/Http/Controllers/Api/Platform/Organizations/OrganizationReservationFieldsController.php, app/Http/Controllers/Api/Platform/OrganizationsController.php, app/Http/Controllers/Api/Platform/ProductReservationsController.php, app/Http/Requests/Api/Platform/Organizations/OrganizationReservationFields/IndexOrganizationReservationFieldsRequest.php, app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationReservationSettingsRequest.php, app/Http/Requests/Api/Platform/ProductReservations/StoreProductReservationRequest.php, app/Http/Resources/OrganizationReservationFieldResource.php, app/Http/Resources/OrganizationResource.php, app/Http/Resources/ProductReservationFieldValueResource.php, app/Http/Resources/ProductReservationResource.php, app/Models/Organization.php, app/Models/OrganizationReservationField.php, app/Models/ProductReservation.php, app/Models/ProductReservationFieldValue.php, app/Models/Voucher.php, app/Policies/OrganizationReservationFieldPolicy.php, app/Services/Forus/TestData/TestData.php, config/forus/test_data/configs/default/config.php, database/migrations/2023_07_25_211454_create_organization_reservation_fields_table.php, database/migrations/2023_07_28_180406_create_product_reservation_field_values_table.php, resources/lang/nl/validation.php, routes/api-platform.php
=> Add custom reservation fields

app/Http/Resources/FundResource.php
Required for https://github.com/teamforus/forus-frontend/pull/2841
=> rename fund global 2fa props

app/Models/Fund.php, app/Models/FundFormulaProduct.php
=> fund formula product fallback inexisting identities

resources/lang/nl/validation.php
=> fix translation

app/Http/Controllers/Api/Platform/Organizations/Implementations/ImplementationPagesController.php, app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationPages/StoreImplementationPageRequest.php, app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationPages/UpdateImplementationPageRequest.php, app/Http/Resources/ImplementationPageResource.php, app/Http/Resources/Sponsor/ImplementationPageResource.php, app/Models/ImplementationPage.php, database/migrations/2023_08_13_215407_add_blocks_per_row_field_to_implementation_pages_table.php
=> add cms blocks per row configuration

app/Http/Requests/Api/Platform/Organizations/Products/IndexProductRequest.php, app/Models/Product.php, app/Scopes/Builders/ProductQuery.php
=> change products page content to table view, add sorting

.env.example, app/Http/Controllers/Api/Platform/FirestoreTokensController.php, app/Http/Requests/Api/Platform/FirestoreTokens/StoreFirestoreTokenRequest.php, app/Models/SystemConfig.php, composer.json, composer.lock, config/forus/seeders/system_configs.php, database/migrations/2023_09_04_131212_create_system_configs_table.php, database/seeders/DatabaseSeeder.php, database/seeders/SystemConfigTableSeeder.php, routes/api-platform.php, storage/firestore/.gitignore, storage/firestore/firestore-context.example.json
=> add system configs table and firestore endpoint

app/Http/Controllers/Api/Platform/FundRequestsController.php, app/Http/Controllers/Api/Platform/Organizations/FundRequestsController.php, app/Http/Requests/Api/Platform/FundRequests/IndexFundRequestsRequest.php, app/Http/Resources/FundRequestClarificationResource.php, app/Http/Resources/Requester/FundRequestResource.php, app/Models/FundRequest.php, app/Policies/FundRequestPolicy.php, app/Searches/FundRequestSearch.php, routes/api-platform.php, tests/Browser/FundRequestTest.php
=> Add fund requests on webshop for requesters

app/Http/Controllers/Api/Platform/Organizations/FundsController.php, app/Http/Requests/Api/Platform/Organizations/Funds/BaseFundRequest.php, app/Http/Requests/Api/Platform/Organizations/Funds/StoreFundRequest.php, app/Http/Requests/Api/Platform/Organizations/Funds/UpdateFundRequest.php, app/Http/Resources/FundResource.php, app/Models/Fund.php, database/migrations/2023_09_15_121241_add_external_page_to_funds.php, resources/lang/nl/validation.php
=> Add external page for external fund

resources/lang/nl/validation.php
=> translation validation.php

app/Http/Resources/Identity2FAResource.php
=> identity 2FA resource small adjustments

app/Http/Controllers/Api/Platform/FundRequests/FundRequestClarificationsController.php, app/Http/Controllers/Api/Platform/FundRequestsController.php, app/Http/Controllers/Api/Platform/Funds/Requests/FundRequestClarificationsController.php, app/Http/Controllers/Api/Platform/Organizations/FundRequests/FundRequestClarificationsController.php, app/Http/Controllers/Api/Platform/Organizations/FundRequestsController.php, app/Http/Requests/Api/Platform/FundRequests/FundRequestClarifications/UpdateFundRequestClarificationRequest.php, app/Http/Requests/Api/Platform/FundRequests/IndexFundRequestsRequest.php, app/Http/Resources/FundRequestClarificationResource.php, app/Http/Resources/Requester/FundRequestResource.php, app/Models/FundRequest.php, app/Notifications/Identities/FundRequest/IdentityFundRequestRecordFeedbackRequestedNotification.php, app/Policies/FundRequestClarificationPolicy.php, app/Policies/FundRequestPolicy.php, app/Searches/FundRequestSearch.php, routes/api-platform.php, tests/Browser/FundRequestTest.php
=> Add fund requests for requesters on webshop

app/Policies/VoucherPolicy.php
Allowed activate external vouchers
=> allow activate external vouchers

app/Http/Resources/Provider/ProviderVoucherTransactionEmployeeResource.php, app/Models/VoucherTransaction.php
=> Adjust days before transaction information for voucher transactions

app/Exports/ProductReservationsExport.php, app/Models/ProductReservation.php
=> Fix birth date in product reservation

app/Http/Controllers/Api/Platform/ReimbursementsController.php
=> Transform iban in reimbursement create to uppercase

app/Mail/Vouchers/VoucherAssignedProductMail.php
=> Fix unexpected string in voucher mail

resources/lang/nl/validation.php
=> Update translations split address

composer.lock
Synchronize composer.lock with composer.json and fix warning 
```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
```
by ```composer update```
=> Synchronize composer.lock with composer.json

app/Models/SystemNotification.php
=> Fix system notification find template error

app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationPages/ValidateImplementationPageBlocksRequest.php, app/Http/Resources/ImplementationBlockResource.php, app/Models/ImplementationBlock.php, app/Models/ImplementationPage.php, database/migrations/2023_10_26_083533_add_button_link_label_text_field_to_implementation_blocks_table.php, tests/Feature/ImplementationCMSTest.php
=> wcag add button link label field for implementation blocks

database/migrations/2023_11_01_150341_fix_type_for_fund_request_clarification_proof_in_files.php
=> Fix file type for fund request clarification upload

app/Http/Resources/SystemNotificationResource.php, app/Models/SystemNotification.php, app/Notifications/BaseNotification.php
=> Fix system notification configs

app/Services/BackofficeApiService/BackofficeApi.php, config/logging.php
=> add backoffice log channel

app/Http/Controllers/BNGController.php, app/Models/BankConnection.php, app/Models/VoucherTransactionBulk.php, app/Services/BNGService/BNGService.php, app/Services/BNGService/Responses/Pagination/PaginationLinks.php
=> bng logs enhancements

app/Http/Controllers/Api/Platform/OrganizationsController.php, database/migrations/2023_10_12_005957_update_business_type_id_non_nullable_from_organizations_table.php, routes/api-platform.php
=> remove business organization type select feature

app/Http/Requests/Api/Platform/Funds/Requests/Records/StoreFundRequestRecordRequest.php, app/Http/Requests/Api/Platform/Organizations/Vouchers/AssignVoucherRequest.php, app/Http/Requests/Api/Platform/Organizations/Vouchers/StoreBatchVoucherRequest.php, app/Http/Requests/Api/Platform/Organizations/Vouchers/StoreVoucherRequest.php, app/Rules/BsnRule.php, tests/Unit/BsnRuleTest.php
=> Update partner bsn validation

resources/lang/nl/states/product_reservations.php, resources/lang/nl/states/reservation_extra_payment_refunds.php, resources/lang/nl/states/reservation_extra_payments.php, resources/lang/nl/validation.php
=> mollie translations

app/Http/Resources/Sponsor/SponsorVoucherResource.php, app/Models/Data/VoucherExportData.php, app/Models/Voucher.php, resources/lang/nl/vouchers.php
=> adjust 'source' and 'state' field values in vouchers export

app/Http/Controllers/Api/Platform/Organizations/Sponsor/TransactionsController.php, app/Http/Requests/Api/Platform/Organizations/Sponsor/Transactions/IndexTransactionsRequest.php, app/Http/Requests/Api/Platform/Organizations/Transactions/BaseIndexTransactionsRequest.php, app/Http/Resources/Sponsor/SponsorVoucherTransactionResource.php, app/Models/VoucherTransaction.php, app/Models/VoucherTransactionBulk.php, app/Searches/VoucherTransactionsSearch.php
=> Add reservations to voucher details page

app/Scopes/Builders/VoucherQuery.php
=> Add voucher search by voucher record values

config/forus/digid.php
=> rename digid saml env var

app/Http/Requests/Api/Platform/ProductReservations/StoreProductReservationRequest.php
=> add custom message for birth date in reservation store

app/Http/Controllers/Api/Platform/Organizations/Sponsor/ReservationExtraPaymentsController.php
=> Show only paid and not refunded extra payments for sponsor

app/Exports/VoucherExport.php, app/Http/Requests/Api/Platform/Organizations/Vouchers/IndexVouchersRequest.php, app/Http/Resources/Sponsor/SponsorVoucherResource.php, app/Models/Data/VoucherExportData.php, app/Models/Voucher.php
=> Add horizontal scrolling and implementation filter to vouchers tables

app/Exports/VoucherExport.php, app/Http/Requests/Api/Platform/Organizations/Vouchers/IndexVouchersRequest.php, app/Http/Resources/Sponsor/SponsorVoucherResource.php, app/Models/Data/VoucherExportData.php, app/Models/Voucher.php
Reverts teamforus/forus-backend#2046
=> Revert "Add horizontal scrolling and implementation filter to vouchers tables"

app/Rules/BsnRule.php
=> Fix bsn validation rule for leading zero values

config/forus/test_data/configs/default/organizations.php
=> update seeder to allow pre-checks for some sponsors

app/Services/BackofficeApiService/BackofficeApi.php
=> Add response body for backoffice api exception logs

tests/Feature/VoucherTransactionNoteTest.php
=> Add voucher transaction note test

.github/workflows/browser_tests.yml
temporarily turn off browser tests auto triggers until they are fixed
=> turn off browser tests

app/Http/Controllers/Api/Platform/Organizations/ProductReservationsController.php, app/Http/Resources/ProductReservationResource.php, app/Models/ProductReservation.php, app/Policies/ProductReservationPolicy.php, app/Policies/VoucherPolicy.php, app/Searches/ProductReservationsSearch.php, tests/Browser/ProductReservationTest.php
=> Show to provider reservations with expired vouchers as archived

app/Http/Requests/Api/Platform/Organizations/Implementations/PreChecks/SyncPreCheckRequest.php, app/Http/Resources/ImplementationPreChecksResource.php
=> fund pre-check adjustments and fixes

app/Http/Controllers/Api/IdentityController.php, app/Http/Requests/Api/Contact/SendContactFormRequest.php, app/Http/Requests/Api/Identity/Emails/StoreIdentityEmailRequest.php, app/Http/Requests/Api/IdentityAuthorizationEmailTokenRequest.php, app/Http/Requests/Api/IdentityStoreRequest.php, app/Http/Requests/Api/Platform/Feedback/StoreFeedbackRequest.php, app/Http/Requests/Api/Platform/Organizations/Employees/StoreEmployeeRequest.php, app/Http/Requests/Api/Platform/Organizations/MollieConnectionProfiles/BaseMollieConnectionProfileRequest.php, app/Http/Requests/Api/Platform/Organizations/MollieConnections/StoreMollieConnectionRequest.php, app/Http/Requests/Api/Platform/Organizations/Offices/BaseOfficeRequest.php, app/Http/Requests/Api/Platform/Organizations/StoreOrganizationRequest.php, app/Http/Requests/Api/Platform/Organizations/UpdateOrganizationRequest.php, app/Http/Requests/Api/Platform/Organizations/Vouchers/AssignVoucherRequest.php, app/Http/Requests/Api/Platform/Organizations/Vouchers/IndexVouchersRequest.php, app/Http/Requests/Api/Platform/Organizations/Vouchers/SendVoucherRequest.php, app/Http/Requests/Api/Platform/Organizations/Vouchers/StoreBatchVoucherRequest.php, app/Http/Requests/Api/Platform/Organizations/Vouchers/StoreVoucherRequest.php, app/Http/Requests/Api/Platform/Reimbursements/StoreReimbursementRequest.php, app/Http/Requests/Api/Platform/Reimbursements/UpdateReimbursementRequest.php, app/Http/Requests/Api/Platform/Share/ShareEmailRequest.php, app/Http/Requests/Api/Records/RecordStoreRequest.php, app/Http/Requests/BaseFormRequest.php
=> Update email validation filter utf8

app/Http/Requests/Api/Platform/Organizations/Products/BaseProductRequest.php, app/Http/Resources/OrganizationResource.php
=> Show extra payment config for provider if mollie onboarding complete

app/Http/Resources/ProductReservationResource.php, app/Http/Resources/ReservationExtraPaymentResource.php, app/Models/ProductReservation.php, app/Models/ReservationExtraPayment.php, app/Models/ReservationExtraPaymentRefund.php, app/Policies/ProductReservationPolicy.php, app/Scopes/Builders/ReservationExtraPaymentQuery.php, database/migrations/2023_12_29_041513_add_expired_state_to_reservation_extra_payments_table.php, resources/lang/nl/states/reservation_extra_payments.php
=> Check extra payment refund state when accept or reject reservation

app/Events/MollieConnections/MollieConnectionCurrentProfileChanged.php, app/Http/Controllers/Api/Platform/Organizations/MollieConnectionController.php, app/Http/Controllers/Api/Platform/Organizations/MollieConnectionProfileController.php, app/Http/Requests/Api/Platform/Organizations/MollieConnectionProfiles/ChangeMollieConnectionCurrentProfileRequest.php, app/Http/Requests/Api/Platform/Organizations/MollieConnections/UpdateMollieConnectionRequest.php, app/Http/Resources/MollieConnectionProfileResource.php, app/Http/Resources/MollieConnectionResource.php, app/Listeners/MollieConnectionSubscriber.php, app/Policies/MollieConnectionPolicy.php, app/Policies/MollieConnectionProfilePolicy.php, app/Services/MollieService/Models/MollieConnection.php, routes/api-platform.php
=> Add select payment profile for mollie

app/Http/Requests/Api/Platform/Organizations/MollieConnectionProfiles/BaseMollieConnectionProfileRequest.php, app/Http/Requests/Api/Platform/Organizations/MollieConnections/StoreMollieConnectionRequest.php
=> Add validation for mollie connection profile phone

app/Http/Requests/Api/Platform/Organizations/Provider/IndexFundProviderRequest.php, app/Models/FundProvider.php
=> Add filter providers by extra payments allowed by sponsor

app/Scopes/Builders/ReservationExtraPaymentQuery.php
=> Fix duplicate column in reservation extra payments filter

app/Http/Requests/Api/Platform/Organizations/Implementations/PreChecks/SyncPreCheckRequest.php
=> Pre-check adjustments and fixes

app/Http/Controllers/Api/Platform/Organizations/ImplementationsController.php, app/Http/Resources/ImplementationResource.php, app/Policies/ImplementationPolicy.php, database/seeders/PermissionsTableSeeder.php, database/seeders/RolePermissionsTableSeeder.php
=> Add permission to view public implementation information

app/Http/Resources/OrganizationFeaturesResource.php
=> Add new pages to features marketplace

app/Http/Controllers/Api/Platform/Organizations/Provider/TransactionsController.php, app/Http/Resources/FundResource.php, app/Http/Resources/Provider/ProviderVoucherTransactionResource.php, app/Http/Resources/Small/FundSmallResource.php, app/Http/Resources/Sponsor/SponsorVoucherTransactionResource.php, app/Http/Resources/VoucherTransactionBulkResource.php, app/Models/ProductReservation.php, app/Models/VoucherTransaction.php, app/Rules/ProductReservations/ProviderProductReservationBatchRule.php, config/forus/test_data/configs/default/funds.php
react provider dashboard update
=> react provider dashboard update

app/Http/Controllers/Api/Platform/Organizations/Sponsor/TransactionsController.php, app/Http/Resources/Sponsor/SponsorVoucherTransactionResource.php
=> update resources for react sponsor dashboard

app/Http/Resources/MollieConnectionResource.php
=> Add missing fields in mollie connection resource

app/Providers/AppServiceProvider.php, tests/Browser/ProductReservationTest.php, tests/Browser/ReimbursementTest.php
=> update dusk attributes

app/Providers/AppServiceProvider.php, tests/DuskTestCase.php
=> move dusk selector from service provider to dusk base class

database/seeders/RolePermissionsTableSeeder.php, database/seeders/RolesTableSeeder.php
Removed two outdated roles, on production and other envs they are already deleted
=> removed implementation manager roles

app/Helpers/Locker.php, app/Http/Requests/Api/Platform/Organizations/ProductReservations/AcceptProductReservationRequest.php, config/forus/throttles.php, resources/lang/nl/throttles/accept_reservation.php
=> throttle reservation accept endpoint

app/Policies/OrganizationPolicy.php
=> update organization features endpoint policy

resources/views/pdf/pre_check_totals.blade.php
=> translations pre_check_totals.blade.php

app/Listeners/ReservationExtraPaymentSubscriber.php, app/Mail/ProductReservations/ProductReservationCanceledMail.php, app/Mail/ProductReservations/ProductReservationRejectedMail.php, app/Notifications/Identities/ProductReservation/IdentityProductReservationCanceledNotification.php, app/Notifications/Identities/ProductReservation/IdentityProductReservationRejectedNotification.php, database/seeders/SystemNotificationsTableSeeder.php, database/seeders/resources/mail_templates/notification_templates.json, database/seeders/resources/mail_templates/notifications_identities/product_reservation_canceled.md, database/seeders/resources/mail_templates/notifications_identities/product_reservation_rejected.md, database/seeders/resources/mail_templates/notifications_products/reservation_refund_reminder.md, resources/lang/nl/mails/reservations.php
=> Add mail notifications for product reservation cancel or reject

resources/views/pdf/pre_check_totals.blade.php
=> fix pre-check pdf table width

database/seeders/RolePermissionsTableSeeder.php
Added missing view_implementations permission to two roles
=> added missing permissions to seeder

app/Searches/EmployeeEventLogSearch.php, config/forus/event_permissions.php
=> Fix event logs search for employees relation

app/Models/PreCheck.php
=> fix precheck knock when multiple funds

app/Http/Requests/Api/Platform/Organizations/Implementations/PreChecks/SyncPreCheckRequest.php, app/Http/Resources/ImplementationPreChecksResource.php, app/Models/PreCheck.php, app/Models/RecordType.php, database/migrations/2024_02_28_191454_add_pre_check_field_to_record_types_table.php
=> Add a flag for toggling record types in pre-check

resources/views/pdf/pre_check_totals.blade.php
=> minor precheck pdf translation

app/Models/PreCheck.php
=> Add fund logo on the pre-check results page

app/Http/Resources/ImplementationPreChecksResource.php
=> Exclude archived and non-active funds criteria

app/Models/Reimbursement.php
=> Fix store reimbursement note

app/Models/Prevalidation.php, database/migrations/2024_03_08_065109_add_fund_id_and_organization_id_index_to_prevalidations_table.php
=> optimize prevalidations list loading time

app/Models/VoucherTransaction.php
=> Small fix for payment description generation

app/Http/Resources/FundCriterionResource.php, app/Http/Resources/FundResource.php, app/Http/Resources/OrganizationResource.php, app/Models/Organization.php
=> optimize funds list endpoint

app/Services/BNGService/BNGService.php, app/Services/BNGService/Responses/BulkPaymentValue.php, app/Services/BNGService/Responses/Value.php
added /status endpoint code from Valentin for BNG debugging of bulk payments
=> added getBulkDetailsStatus endpoint

app/Http/Resources/FundResource.php, app/Models/Fund.php, database/seeders/RecordTypesTableSeeder.php
=> Add children count to financial overview

app/Exports/FundsExport.php, resources/lang/nl/export.php
=> Add children count to financial statistic export

app/Models/Office.php, database/migrations/2024_04_02_134220_change_branch_number_column_offices_table.php
=> fix office logo edit, update office branch number validation rules

app/Models/VoucherTransaction.php, database/migrations/2024_04_04_125901_add_soft_delete_columnt_to_voucher_transactions.php
=> Add soft delete to voucher transactions

app/Models/VoucherTransaction.php
=> Fix bank statement description truncation

app/Models/VoucherTransaction.php
=> fix payment description for direct transactions

app/Models/FundRequest.php, public/.htaccess, resources/lang/nl/export.php, resources/lang/nl/policies/fund_requests.php, tests/Browser/AuthenticationTest.php, tests/Browser/ReimbursementTest.php
=> React.webshop

app/Models/Fund.php
=> fix backoffice connections for product funds

app/Models/VoucherTransactionBulk.php, app/Searches/VoucherTransactionBulksSearch.php
=> Fix voucher transaction bulks search with empty filter values

app/Services/Forus/Notification/Repositories/NotificationRepo.php
=> Fix notification preferences toggle

app/Http/Resources/VoucherTransactionBulkResource.php, app/Policies/VoucherTransactionBulkPolicy.php
=> Add voucher transactions cost locale to transaction bulk resource

app/Http/Controllers/Api/Platform/NotificationsController.php
=> Fix notification mark as read

app/Http/Resources/OrganizationFeaturesResource.php
=> Add marketplace pages for funds and voucher topup

app/Services/BIConnectionService/Models/BIConnection.php
=> Allow token reset for disabled BI connections

app/Http/Resources/FundFormulaResource.php, app/Http/Resources/FundResource.php, app/Models/FundFormula.php
=> Add fund formulas tab to funds show page

app/Http/Controllers/Api/Platform/Organizations/Sponsor/VouchersController.php, app/Http/Requests/Api/Platform/Organizations/Vouchers/IndexVouchersRequest.php, app/Policies/VoucherPolicy.php, app/Policies/VoucherRecordPolicy.php, database/seeders/PermissionsTableSeeder.php, database/seeders/RolePermissionsTableSeeder.php, database/seeders/RolesTableSeeder.php
=> Add permission to only view vouchers

app/Http/Controllers/Api/Platform/Organizations/MollieConnectionController.php, app/Policies/ProductReservationPolicy.php, app/Services/MollieService/MollieServiceTest.php, tests/Feature/MollieExtraPaymentsTest.php, tests/Feature/MollieServiceTest.php
=> Add tests for mollie payment method

tests/Browser/AuthenticationTest.php, tests/Browser/EmployeeTest.php, tests/Browser/IdentityEmailTest.php, tests/Browser/ReimbursementTest.php, tests/Browser/Traits/HasFrontendActions.php, tests/Browser/VoucherBatchTest.php, tests/Browser/VoucherTransactionBatchTest.php
Update dusk tests to support react sponsor and small optimizations
=> update dusk tests for react sponsor panel

.github/workflows/auto_pr_on_master_push.yml
When there are no changes between master and develop, only merge commits from PRs, there will be no PR
=> Not create pr when no changes

Dockerfile, composer.json, composer.lock, docker/docker-compose/php/Dockerfile
bump PHP to 8.2 + regenerate composer.lock
=> Up php version to 8.2

app/Http/Controllers/Api/Platform/Organizations/ImplementationsController.php, app/Http/Requests/Api/Platform/Organizations/Implementations/UpdateImplementationCmsRequest.php, app/Http/Resources/ImplementationPrivateResource.php, app/Models/Implementation.php, database/migrations/2024_07_17_152117_add_page_title_suffix_to_implementations.php
=> Add page title suffix to implementation cms for wcag

tests/Browser/MarkdownTableCaptionAndHeadersTest.php, tests/Traits/MakesTestFunds.php
=> dusk tests for markdown h4 to caption transformation

app/Scopes/Builders/ReservationExtraPaymentQuery.php, app/Searches/ReservationExtraPaymentsSearch.php
=> Fix reservation extra payments sorting

app/Console/Kernel.php
=> Change cron time for low fund balance

resources/views/pages/auth/deep_link.blade.php, resources/views/pages/layout.blade.php, resources/views/pages/notifications/subscribed.blade.php, resources/views/pages/notifications/unsubscribed.blade.php
=> Add react to auth page

app/Http/Controllers/Api/Platform/Organizations/Sponsor/ProvidersController.php, app/Http/Requests/Api/Platform/Organizations/Sponsor/Providers/IndexProvidersRequest.php, app/Scopes/Builders/OrganizationQuery.php
=> Add state group filter to sponsor providers

tests/Browser/VoucherBatchTest.php
=> update dusk tests for voucher batch upload

app/Http/Controllers/Api/Platform/Organizations/Implementations/ImplementationPagesController.php, app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationPages/StoreImplementationPageRequest.php, app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationPages/UpdateImplementationPageRequest.php, app/Http/Requests/Api/Platform/Organizations/Implementations/IndexImplementationRequest.php, app/Http/Resources/ImplementationPageResource.php, app/Http/Resources/Sponsor/ImplementationPageResource.php, app/Models/ImplementationPage.php, database/migrations/2024_08_02_233211_add_title_column_to_implementation_pages_table.php
=> home page products block cms

app/Http/Controllers/Api/Platform/OrganizationsController.php, app/Http/Requests/Api/Platform/Organizations/UpdateBankStatementFieldsRequest.php, app/Http/Resources/OrganizationResource.php, app/Models/Organization.php, app/Models/VoucherTransaction.php, database/migrations/2024_08_09_111710_add_bank_separator_to_organizations.php, tests/Unit/PaymentDescriptionTest.php
=> Add bank separator to organizations for payment description

resources/lang/nl/events/voucher.php
=> Add translation for physical card requested event

app/Http/Controllers/Api/Platform/Organizations/FundsController.php, app/Http/Requests/Api/Platform/Organizations/Funds/BaseFundRequest.php, app/Http/Resources/FundResource.php, app/Http/Resources/Provider/App/ProviderVoucherResource.php, app/Models/Fund.php, app/Models/FundConfig.php, database/migrations/2024_08_06_153600_add_voucher_amount_visible_field_to_fund_configs_table.php, tests/Feature/VouchersProviderMeAppTest.php
=> add voucher amount visible field to funds

.env.docker, .env.docker.dusk, .github/workflows/browser_tests.yml, .github/workflows/unit_and_feature_tests.yml, Dockerfile, docker/cmd/start-docker-compose.sh, docker/cmd/stop-docker-compose.sh, readme-docker.md
- added missing dependency to docker files
- updated Dockerfiles links to react frontends
=> update docker files for react

app/Rules/FundRequests/FundRequestRecords/FundRequestRecordFilesRule.php, tests/Unit/FundRequestRuleTest.php
=> Update fund request validation files if criteria is optional

database/seeders/RolesTableSeeder.php
=> Update role seeder texts

app/Exports/VoucherTransactionsProviderExport.php, app/Models/VoucherTransaction.php
=> Add fields to provider transaction export

app/Http/Resources/IdentityResource.php
=> fix identity bsn time not being absolute

app/Http/Resources/Sponsor/SponsorVoucherTransactionResource.php, app/Models/VoucherTransaction.php, app/Searches/VoucherTransactionsSearch.php
=> Add sort for voucher transaction payment type

app/Services/EventLogService/Models/EventLog.php
=> fix logs message

app/Searches/VoucherTransactionsSearch.php, resources/lang/nl/transaction.php
=> fix payment type translation

tests/Browser/VoucherBatchTest.php, tests/Feature/VoucherBatchTest.php, tests/Feature/VoucherTest.php, tests/TestCases/VoucherBatchTestCases.php, tests/TestCases/VoucherTestCases.php
Changed vouchers and batch tests and arrays names to more speaking so in the list of passed test you can see names instead of numbers
@dev-rminds @ateamcms This PR is optional, so if idea is not good, please feel free to close it
=> Rename numbered test cases to words

app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationPages/ValidateImplementationPageBlocksRequest.php, database/migrations/2024_09_12_191535_update_implementation_blocks_table_columns_max_length.php, tests/Feature/ImplementationCMSTest.php
=> decrease the max lenth for implementation block fields

database/migrations/2024_08_15_033657_add_custom_amount_and_preset_fields_to_fund_configs_table.php
=> Bugfix.add missing rollback field

app/Models/Fund.php
=> fix fund requests without formula

app/Http/Resources/FundCriteriaStepResource.php, app/Models/FundConfig.php, app/Models/FundCriteriaStep.php, app/Services/Forus/TestData/TestData.php, database/migrations/2024_09_23_101833_add_description_to_fund_criteria_steps_table.php
=> add step description to fund request overview

app/Http/Requests/Api/Platform/Prevalidations/UploadPrevalidationsRequest.php, app/Rules/PrevalidationDataItemRule.php, app/Rules/PrevalidationDataRule.php
=> Add record type validation for csv prevalidations data

app/Console/Commands/NotifyAboutVoucherExpireCommand.php, app/Scopes/Builders/VoucherQuery.php, resources/lang/nl/events/voucher.php, tests/Feature/VoucherExpireSoonNotificationTest.php
=> fix duplicate voucher expire soon notification

app/Models/Announcement.php, app/Models/Implementation.php, app/Searches/AnnouncementSearch.php, database/migrations/2024_09_13_120600_add_columns_to_announcements.php, tests/Feature/AnnouncementTest.php, tests/TestCase.php, tests/Traits/MakesTestFunds.php
=> Announcement improvements

tests/Feature/VoucherTransactionTransferDaysTest.php, tests/Traits/MakesProductReservations.php
=> fixes for product reservation tests and voucher transaction note tests

app/Models/Fund.php, app/Models/FundConfig.php, app/Models/Record.php, app/Scopes/Builders/RecordValidationQuery.php, database/migrations/2024_08_30_123532_add_records_trust_start_date_to_fund_configs_table.php, tests/Unit/FundTrustedRecordsTest.php
=> add fund record validations start date

app/Scopes/Builders/ProductQuery.php, tests/Feature/ProductExclusionsTest.php
=> Fix product visibility on webshop if excluded from fund by provider

app/Http/Requests/Api/Platform/Organizations/Funds/BaseFundRequest.php, app/Http/Resources/FundCriterionResource.php, app/Models/Fund.php, app/Models/FundCriterion.php, database/migrations/2024_09_27_175002_add_label_to_fund_criteria_table.php
=> Fund criteria label

app/Models/Implementation.php
=> fix general implementation resource

app/Models/FundRequest.php
=> UX improvements to the fund request page

app/Http/Requests/Api/Platform/Organizations/Funds/BaseFundRequest.php, app/Http/Resources/FundCriterionResource.php, app/Models/Fund.php, app/Models/FundCriterion.php, database/migrations/2024_10_12_124453_add_extra_description_to_fund_criteria.php
=> Add extra description to fund criteria

app/Searches/FundRequestSearch.php
=> fix sorting fund-requests by assigned employee

tests/Browser/ReimbursementTest.php, tests/Browser/Traits/HasFrontendActions.php, tests/Browser/VoucherBatchTest.php
=> fix dusk tests

app/Providers/RouteServiceProvider.php, routes/api-platform.php
=> fix vouchers endpoint for me-app

composer.lock, docker/docker-compose/php/Dockerfile
@dev-rminds I did not increase version of PHP in composer.json to 8.3 to keep compatibility, but if you think we should I can add it
=> upgrade php in docker to 8.3 and add composer update

config/forus/tests.php
=> increase default dusk wait for time

app/Console/Kernel.php, config/forus/sessions.php
Fixed an incorrect configuration key and renamed an environment variable for better clarity.
=> fix disable_auth_expiration flag

app/Http/Resources/Provider/ProviderVoucherTransactionEmployeeResource.php, app/Http/Resources/Provider/ProviderVoucherTransactionResource.php, app/Http/Resources/VoucherTransactionResource.php, app/Models/VoucherTransaction.php, app/Scopes/Builders/VoucherTransactionQuery.php
=> fix transaction transfer in days display issue

app/Mail/User/EmployeeAddedMail.php, resources/lang/nl/digests/validator.php
=> Changed the terms used (dashboard --> beheeromgeving)

app/Http/Resources/OrganizationWithPrivateResource.php
=> fix kvk key

app/Exports/ProductReservationsExport.php, app/Http/Requests/Api/Platform/Organizations/Products/BaseProductRequest.php, app/Http/Requests/Api/Platform/Organizations/Products/StoreProductRequest.php, app/Http/Requests/Api/Platform/Organizations/Products/UpdateProductRequest.php, app/Http/Resources/Provider/ProviderProductResource.php, app/Http/Resources/Sponsor/SponsorProviderProductResource.php, app/Listeners/ProductSubscriber.php, app/Models/Product.php, app/Rules/EanCodeRule.php, app/Scopes/Builders/ProductQuery.php, database/migrations/2024_10_31_183326_add_ean_and_sku_columns_to_products.php, resources/lang/nl/validation.php
=> Add sku and ean columns to product

.github/workflows/browser_tests.yml
=> remove debug dusk

app/helpers.php
=> fix notifications with non string logs

app/Console/Commands/NotifyAboutReachedNotificationFundAmount.php, app/Statistics/Funds/FinancialOverviewStatisticQueries.php, tests/Feature/FundStatisticsTest.php
=> fix funds total statistics

app/Exports/FundsExport.php, app/Http/Controllers/Api/Platform/Organizations/FundsController.php, app/Statistics/Funds/FinancialOverviewStatistic.php, app/Statistics/Funds/FinancialOverviewStatisticQueries.php
=> remove financial overview year filter

app/Http/Controllers/Api/Platform/FundsController.php, app/Http/Requests/Api/Platform/Funds/ViewFundRequest.php, app/Models/Fund.php
=> update view fund policy

app/Services/Forus/TestData/TestData.php, config/forus/test_data/configs/default/record_types.php, database/seeders/RecordTypesTableSeeder.php
=> update seeder after adding control_type column to record types

.github/dependabot.yaml
changed base branch for security updates to develop
added dependency only major updates for composer
=> add dependabot for the backend

app/Http/Requests/Api/Identity/Emails/StoreIdentityEmailRequest.php, app/Rules/IdentityEmailMaxRule.php, config/forus/mail.php, resources/lang/nl/validation.php, tests/Feature/IdentityEmailTest.php
=> Add max emails rule for identity

app/Exceptions/Handler.php, resources/lang/nl/exceptions.php
=> Add not found messages when model not found

app/Http/Resources/Sponsor/SponsorVoucherResource.php, app/Models/Voucher.php, app/Models/VoucherTransactionBulk.php, tests/Feature/MollieExtraPaymentsTest.php, tests/Feature/ProductFundLimitsTest.php, tests/Feature/ProductReservationTest.php, tests/Feature/VoucherHasPayoutTest.php, tests/Feature/VoucherTransactionTransferDaysTest.php, tests/Traits/MakesTestBankConnections.php, tests/Traits/TestsReservations.php
=> Update voucher has_payouts getter

tests/Feature/VoucherTest.php
Case: https://github.com/teamforus/forus-backend/actions/runs/12279014756/attempts/1
=> fix flaky test case

database/seeders/resources/mail_templates/notification_templates.json, database/seeders/resources/mail_templates/notifications_identities/fund_request_disregarded.md, database/seeders/resources/mail_templates/notifications_identities/fund_request_disregarded_informal.md, database/seeders/resources/mail_templates/notifications_products/reservation_refund_reminder.md, database/seeders/resources/mail_templates/notifications_products/sold_out.md
=> small changes in system messages

app/Policies/VoucherPolicy.php
=> Hide share voucher button for budget voucher

app/Searches/VoucherTransactionsSearch.php
=> Fix transactions filter

app/Models/Implementation.php
=> Add dashboard sign up urls to implementation config

app/Http/Requests/Api/Platform/Organizations/Sponsor/Payouts/IndexPayoutTransactionsRequest.php, app/Http/Requests/Api/Platform/Organizations/Vouchers/IndexVouchersRequest.php, app/Models/Voucher.php, app/Models/VoucherTransaction.php
=> fix sorting on vouchers and requests table for sponsor

app/Http/Requests/Api/Platform/Organizations/Vouchers/IndexVouchersRequest.php, app/Models/Voucher.php
=> fix default voucher sorting

app/Listeners/FundRequestSubscriber.php, app/Scopes/Builders/FundRequestQuery.php
=> fix regress related to identity id migration

app/Http/Controllers/Api/Platform/FundRequestsController.php, app/Http/Controllers/Api/Platform/Funds/FundRequestsController.php, app/Http/Controllers/Api/Platform/Organizations/FundRequestsController.php, app/Http/Controllers/Api/Platform/PayoutsController.php, app/Http/Requests/Api/Platform/Funds/Requests/IndexFundRequestsRequest.php, app/Http/Requests/Api/Platform/Organizations/Vouchers/IndexVouchersRequest.php, app/Listeners/FundRequestSubscriber.php, app/Models/Fund.php, app/Models/FundRequest.php, app/Models/Identity.php, app/Models/Voucher.php, app/Notifications/Identities/FundRequest/BaseIdentityFundRequestNotification.php, app/Policies/FundRequestClarificationPolicy.php, app/Policies/FundRequestPolicy.php, app/Policies/FundRequestRecordPolicy.php, app/Scopes/Builders/FundRequestQuery.php, app/Searches/FundRequestSearch.php, database/migrations/2024_12_19_073533_add_identity_id_to_fund_requests_table.php, tests/Browser/FundRequestTest.php
=> Fund request identity

app/Console/Commands/BankProcessFundTopUpsCommand.php
=> fix top-up command

public/.htaccess
/server-status URL is needed for apache monitoring, excluded it from rewrite to fix
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Not Found</title>
<style>
...
```
=> exclude server-status request for monitoring

app/Digests/ProviderFundsDigest.php, app/Http/Resources/VoucherResource.php, app/Http/Resources/VoucherTransactionResource.php, app/Listeners/FundSubscriber.php, app/Models/FundFormula.php, app/Models/Implementation.php, app/Models/Product.php, app/Models/Reimbursement.php, app/Services/EventLogService/EventLogService.php, app/helpers.php, database/migrations/2025_01_16_110015_drop_currency_sign_and_currency_round_from_implementations_table.php, tests/Browser/ReimbursementTest.php
=> remove currency_sign feature

app/Models/ProductCategory.php, app/Statistics/Funds/FinancialStatisticQueries.php, database/seeders/ProductCategoriesTableSeeder.php, tests/Feature/SponsorFinancialStatisticsTest.php, tests/TestCases/SponsorFinancialStatisticsTestCases.php, tests/Traits/MakesTestProducts.php
=> Add tests for financial statistics

app/Statistics/Funds/FinancialOverviewStatistic.php, app/Statistics/Funds/FinancialOverviewStatisticQueries.php, tests/Feature/FundStatisticsOverview/FundStatisticsOverviewBudgetVouchersTest.php, tests/Feature/FundStatisticsOverview/FundStatisticsOverviewProductVouchersTest.php
=> Add tests for fund statistics overview

tests/Browser/ReimbursementTest.php, tests/Browser/Traits/HasFrontendActions.php
=> remove dusk pause

app/Services/QueryCounterService/Data/QueryCounter.php
=> fix get member function get name on null

resources/lang/nl/validation.php
=> translation for email already used

app/helpers.php
Recover accidentally deleted currency symbol here: https://github.com/teamforus/forus-backend/pull/2471
=> restore removed currency symbol

tests/Browser/VoucherBatchTest.php
https://github.com/teamforus/forus-backend/actions/runs/13034063660/job/36360003908
=> fix flacky dusk test

composer.json, composer.lock, pint.json
=> add laravel pint

tests/Browser/EmployeeTest.php, tests/Browser/ProductReservationTest.php, tests/Browser/ReimbursementTest.php, tests/Browser/VoucherBatchTest.php, tests/Browser/VoucherTransactionBatchTest.php
=> fix dusk tests after panel sidebar redesign

app/Http/Controllers/Api/StatusController.php, app/Http/Middleware/ImplementationKeyMiddleware.php, app/Http/Requests/BaseFormRequest.php, app/Models/Implementation.php, app/Services/TranslationService/Traits/HasOnDemandTranslations.php, tests/Feature/ApiHeadersTest.php, tests/Unit/TranslationLimitsTest.php
=> fix and add test for translation limits

app/Http/Controllers/Api/Platform/Organizations/FundRequestsController.php, app/Models/FundRequest.php, app/Services/IConnectApiService/IConnect.php, config/logging.php
=> add iconnect log channel

app/Exports/BaseFieldedExport.php, app/Exports/IdentityProfilesExport.php, app/Exports/VoucherTransactionsSponsorExport.php, app/Http/Controllers/Api/Platform/Organizations/Sponsor/IdentitiesController.php, app/Http/Requests/Api/Platform/Organizations/Sponsor/Identities/IndexIdentitiesRequest.php, app/Http/Requests/Api/Platform/Organizations/Sponsor/Identities/UpdateIdentityRequest.php, app/Http/Resources/Sponsor/SponsorIdentityResource.php, app/Models/ProfileRecord.php, app/Searches/Sponsor/IdentitiesSearch.php, app/Services/Forus/TestData/TestData.php, config/forus/test_data/configs/default/config.php, config/forus/test_data/configs/default/funds.php, database/seeders/RecordTypesTableSeeder.php, routes/api-platform.php, tests/Unit/FundRequestRuleTest.php
=> Extend profile records

app/Http/Requests/Api/Platform/Organizations/Funds/UpdateFundRequest.php, app/Http/Requests/Api/Platform/Organizations/Implementations/ImplementationPages/ValidateImplementationPageBlocksRequest.php, app/Http/Requests/Api/Platform/Organizations/Implementations/UpdateImplementationCmsRequest.php, app/Rules/MaxStringRule.php, resources/lang/nl/validation.php, tests/Feature/ImplementationCMSTest.php
=> Add used characters count in validation message for max rule

app/Statistics/Funds/FinancialOverviewStatisticQueries.php, tests/Feature/FundStatisticsOverview/FundStatisticsOverviewBudgetVouchersTest.php, tests/Feature/FundStatisticsOverview/FundStatisticsOverviewProductVouchersTest.php, tests/Feature/SponsorFinancialStatisticsTest.php, tests/Traits/MakesTestFundProviders.php, tests/Traits/MakesTestProducts.php
=> update statistics formula and statistics feature tests

app/Console/Commands/UpdateNotificationTemplatesCommand.php, app/Mail/Funds/ProviderApprovedMail.php, app/Mail/Funds/ProviderRejectedMail.php, app/Mail/Funds/ProviderStateAcceptedMail.php, app/Mail/Funds/ProviderStateRejectedMail.php, app/Mail/Vouchers/ProductBoughtProviderMail.php, app/Mail/Vouchers/ProductSoldOutMail.php, app/Notifications/Organizations/FundProviders/FundProvidersRevokedBudgetNotification.php, database/seeders/NotificationTemplatesTableSeeder.php, database/seeders/resources/mail_templates/notifications_fund_providers/approved_budget.md, database/seeders/resources/mail_templates/notifications_fund_providers/revoked_budget.md, database/seeders/resources/mail_templates/notifications_fund_providers/state_accepted.md, database/seeders/resources/mail_templates/notifications_fund_providers/state_rejected.md, database/seeders/resources/mail_templates/notifications_products/reserved.md
=> update default system notification templates

app/Models/OrganizationReservationField.php
=> Add reservation custom field type boolean

app/Exceptions/Handler.php, resources/lang/nl/exceptions.php
=> Add custom api error messages

app/Console/Commands/Forus/TestDataSeedCommand.php, database/migrations/2025_03_14_120451_add_more_indexes_to_vouchers_table.php
=> statistics optimization

app/Exports/FundIdentitiesExport.php, app/Exports/ProductReservationsExport.php, app/Http/Controllers/Api/Platform/Organizations/FundProviderController.php, app/Http/Controllers/Api/Platform/Organizations/FundRequestsController.php, app/Http/Controllers/Api/Platform/Organizations/Sponsor/ProvidersController.php, app/Http/Controllers/Api/Platform/PrevalidationController.php, app/Http/Requests/Api/Platform/Funds/Requests/IndexFundRequestsRequest.php, app/Http/Requests/Api/Platform/Organizations/Provider/IndexFundProviderRequest.php, app/Http/Requests/Api/Platform/Prevalidations/SearchPrevalidationsRequest.php
=> fix identity and reservation exports

app/Statistics/Funds/FinancialStatisticQueries.php
=> optimize transactions count preview on filters for statistics page

database/seeders/LanguagesTableSeeder.php
=> update language names

.github/dependabot.yaml
=> Update dependabot script

app/Http/Resources/ImplementationPreChecksResource.php, app/Models/PreCheck.php, app/Models/PreCheckRecord.php, app/Services/TranslationService/Models/TranslationValue.php
=> update precheck mobile version design and fix translations

composer.json, composer.lock
=> update bunq sdk version to 1.27.17.30

app/Http/Resources/Sponsor/SponsorVoucherResource.php, tests/Browser/FundActionsTest.php
=> Add employee email to vouchers page

app/Exports/Base/BaseVoucherTransactionsExport.php, app/Exports/VoucherTransactionsProviderExport.php, app/Models/VoucherTransaction.php, app/Scopes/Builders/VoucherTransactionQuery.php, app/Searches/VoucherTransactionsSearch.php, resources/lang/nl/export.php, tests/Browser/Filters/VoucherTransactionsSearchFilterTest.php, tests/Browser/VoucherTransactionsProviderSearchTest.php
=> Add filter transactions by provider note and autotest for transactions search

app/Http/Controllers/Api/Platform/ProductsController.php, app/Http/Requests/Api/Platform/SearchProductsRequest.php, app/Http/Resources/ProductBasicResource.php, app/Http/Resources/ProductResource.php, app/Models/Product.php, app/Searches/ProductCategorySearch.php
=> add webshop payment options filter

app/Exports/IdentityProfilesExport.php, app/Http/Controllers/Api/Platform/Organizations/Sponsor/IdentitiesController.php, app/Http/Requests/Api/Platform/Organizations/Sponsor/Identities/IndexIdentitiesRequest.php, app/Searches/Sponsor/IdentitiesSearch.php
=> make user profiles sortable

app/Exports/Base/BaseVoucherTransactionsExport.php, app/Exports/ProductReservationsExport.php, app/Exports/VoucherTransactionsProviderExport.php, resources/lang/nl/export.php, tests/Traits/MakesProductReservations.php
=> Add transaction id and reservation code to exports

app/Policies/EmployeePolicy.php, tests/Browser/EmployeeTest.php, tests/Browser/Traits/HasFrontendActions.php, tests/Feature/EmployeeTest.php, tests/Feature/Identity2FATest.php, tests/Traits/MakesTest2FA.php
=> Add employee autotest

app/Http/Controllers/Api/Platform/Organizations/PrevalidationController.php, app/Http/Requests/Api/Platform/Organizations/Prevalidations/UploadPrevalidationsRequest.php
=> fix prevalidation policy name

app/Models/Fund.php
=> update isTakenByPartner validation formula

app/Http/Controllers/Api/Platform/Organizations/Sponsor/VouchersController.php, app/Http/Requests/Api/Platform/Organizations/Vouchers/StoreVoucherRequest.php, app/Models/FundBackofficeLog.php, app/Models/Voucher.php, app/Models/VoucherRelation.php, app/Rules/BsnRule.php, app/Services/Forus/TestData/TestData.php, database/migrations/2025_05_20_074255_add_report_type_to_voucher_relations_table.php, database/migrations/2025_05_20_074255_add_voucher_relation_id_to_fund_backoffice_logs_table.php, resources/lang/nl/validation.php, tests/Browser/BackofficeTest.php, tests/Feature/BackofficeTest.php, tests/Traits/TestsBackoffice.php, tests/Unit/BackofficeApiTest.php, tests/Unit/BsnRuleTest.php
=> add backoffice relation report type

app/Models/Voucher.php, app/Scopes/Builders/VoucherQuery.php, app/Scopes/Builders/VoucherSubQuery.php, tests/Unit/VoucherBalanceTest.php
=> Fix voucher amount spent query

app/Models/Product.php
=> Fix product search by reservation option

app/Exports/PrevalidationsExport.php
=> Update prevalidation record filter in exports

app/Searches/PrevalidationSearch.php
=> add all funds option to prevalidations table filter

app/Scopes/Builders/ProductQuery.php
=> Remove product search by provider description

app/Listeners/ProductSubscriber.php, app/Mail/Vouchers/ProductBoughtProviderMail.php, app/Notifications/Organizations/Products/ProductReservedNotification.php
=> Change provider link in product reserved notification

app/Models/FundRequest.php
=> Fix total in formula preview
