teamforus/forus-backend

app/Http/Controllers/Api/Platform/OrganizationsController.php
app/Models/Fund.php
app/Models/Organization.php
app/Services/BunqService/BunqService.php

- Bunq transaction wait until fund has enough topped amount
- Organization owner wasn't able to scan vouchers without being added as employee with scan vouchers permission

bunq transaction wait until fund has enough topped amount

---

app/Http/Controllers/Api/Platform/Organizations/FundsController.php

Current situation: 
Query is perfomed like _SELECT DISTINCT COUNT(*) FROM voucher_transactions GROUP BY organization_id_
Should be: 
_SELECT COUNT(DISTINCT organization_id) FROM voucher_transactions;_

Fixed providers transactions not being counted properly

---

app/Exceptions/AuthorizationJsonException.php
app/Exceptions/Handler.php
app/Models/Fund.php
app/Policies/VoucherPolicy.php
resources/lang/en/validation.php
resources/lang/nl/validation.php

Now the `403` response will provide a json with 2 attributes 
```json
{
"key": "string error code to be used by the app", 
"message": "a string description to be shown to provider"
}
```
The messages may be edited in translation files [validation.voucher.@key@]
List keys:
Add error when voucher is expired
- expired
Add error when product voucher is used.
- product_voucher_used
Add error when provider isn't applied for fund (does not exist in fund_providers)
- provider_not_applied
Add error when provider is pending for fund(not approved yet) (fund_providers state pending)
- provider_pending 
Add error when provider is denied for fund (fund_providers state denied)
- provider_denied 
The fund is not active 
- fund_not_active
Product voucher already used
- product_voucher_used

Feature voucher error handling

---

app/Services/KvkApiService/KvkApi.php

fix for offices from a larger organization trying to apply using the same KVK. We fill in 12345678 for these organization until we have a better fix. Will readd this rule later.

Add todo for reapplying this rule for kvk

---

app/Services/Forus/Notification/NotificationService.php

Sponsor wants to create QR-codes before start date of fund. Does not want to inform users that QR-code has been assigned. Next release we should enable it again.

Disabled product voucher assign mail

---

.github/workflows/run_tests.yml

Now it will be possible to run autotests manually with needed set of backend and frontend branches
https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
( and fixed hardcoded temporary frontend checkout branch )

Add parameter "frontend_branch" for tests

---

database/seeders/LoremDbSeeder.php

Example: 
Should help detect css issues for long names faster on the local environment.

lorem db seeder: make providers, validators and product names longer

---

app/Http/Requests/Api/Identity/Identity2FA/BaseIdentity2FARequest.php
app/Models/Identity2FA.php
app/Models/Identity2FACode.php
database/migrations/2023_07_20_215618_add_state_to_identity_2fa_code.php
database/migrations/2023_07_20_215618_add_status_to_identity_2fa_code.php
tests/Feature/Identity2FATest.php

- sms code invalid if new one created

Add deactivation sms codes for 2fa if created new one

---

app/Services/IConnectApiService/IConnect.php

Due to the fact the Sanbox URL of IConnect is still hardcoded, changing the URL in the database (column 'iconnect_base_url' in fund_configs) has no effect. This is not the case for production.

changed URL of IConnect sandbox

---

app/Http/Requests/Api/Identity/Identity2FA/StoreIdentity2FARequest.php
tests/Feature/Identity2FATest.php

add country prefixes for 2fa phone authentication

---

app/Exceptions/AuthorizationJsonException.php
app/Exceptions/Handler.php
app/Models/VoucherTransactionBulk.php
app/Services/BNGService/Exceptions/ApiException.php
app/Services/DigIdService/Models/DigIdSession.php
app/Services/KvkApiService/KvkApi.php
config/logging.php

- auth and throttle logs removed
- bng, bunq, kvk and digid related logs moved to separate files

separate logs and remove auth and throttle logs

---

app/Models/RecordType.php
app/Rules/FundCriteria/FundCriteriaValueRule.php
app/Rules/FundRequests/BaseFundRequestRule.php
app/Rules/FundRequests/RecordTypes/RecordTypeSelectNumberRule.php
database/migrations/2024_03_06_160409_add_select_number_type_to_record_types_table.php
tests/Feature/FundCriteriaTest.php

add select_number type to record_types

---

.github/workflows/unit_and_feature_tests.yml
docker-compose.yml
phpunit.xml
tests/Feature/VoucherTransactionBatchTest.php

There was a problem that tests executing for 50 mins
Reason of feature tests running for 50 mins was big amount of batches, which runs slowly in CI due to big output (6gb log)
- Decreased batch amount to 150
- Additionally fixed warning of docker compose for deprecated versioning in docker-compose file 
- Regenerated PHPUnit XML with phpunit --migrate-configuration    
- Some minor CI fixes

Fix 50 mins running feature tests in CI

---

app/Services/Forus/Notification/Commands/NotificationsTokensImportCommand.php

Met deprecation warning in prod notification log
Fixed according to https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated

fix deprecated string interpolation

---

app/Http/Controllers/Api/Platform/Organizations/Sponsor/ProvidersController.php
app/Scopes/Builders/FundQuery.php
app/Scopes/Builders/OrganizationQuery.php

Fixed some providers visible on "Action required" and "Active" tab when they should not be visible.
•  "Action Required" tab, should show providers pending for at least one active funds.
•  "Active" tab, should show providers approved for at least one active funds.
•  "Inactive" tab, should show providers rejected for at least one active funds, or having at least one closed or archived fund of any state.

fix providers state group filter

---

.github/workflows/unit_and_feature_tests.yml

Sometimes we have bugs when new fields are missed in rollback script 
Example - https://github.com/teamforus/forus-backend/pull/2315
If it is missed, we will have see an error in migrations rollback on dev
I added rollback of last 10 migrations to feature tests in CI to check this scenario, it added approx 2 seconds to CI, what is minor amount

add rollback to ci

---

tests/Browser/ReimbursementTest.php

There was a case when faker was generating a name with apostrophe ', for example - O'Connor
This was failing backend validation of iban name
Example of build
https://github.com/teamforus/forus-backend/actions/runs/11050014075/job/30707102258?pr=2330#step:17:1530
Screenshot

remove apostrophe from name generation in Reimbursement test

---

.github/workflows/browser_tests.yml
.github/workflows/unit_and_feature_tests.yml
tests/Browser/Traits/HasFrontendActions.php

Browser tests build is automatically executed in PR creation in branch feature.1
- Build clones backend branch feature.1
- Build checks if there is branch feature.1 in the frontend repo:
- if there is - it uses it for cloning frontend repo
- if there isn't - it uses develop branch
If tests build was executed manually, then it uses frontend branch parameter

Get same branch from frontend for browser CI tests

---

app/Services/MailDatabaseLoggerService/migrations/2024_10_11_101833_add_index_to_mailable_on_email_logs_table.php
database/migrations/2024_10_11_101833_add_index_on_mailable_for_email_logs.php

To fix this slow query
```
SELECT count(*) as aggregate FROM `email_logs` WHERE `mailable` in ('App\\Mail\\Funds\\FundRequests\\FundRequestDeniedMail', 'App\\Mail\\Funds\\FundRequests\\FundRequestCreatedMail', 'App\\Mail\\Funds\\FundRequests\\FundRequestApprovedMail', 'App\\Mail\\Funds\\FundRequests\\FundRequestDisregardedMail', 'App\\Mail\\Funds\\FundRequestRecords\\FundRequestRecordDeclinedMail', 'App\\Mail\\Funds\\FundRequestClarifications\\FundRequestClarificationRequestedMail') and exists (SELECT * FROM `event_logs` WHERE `email_logs`.`event_log_id` = `event_logs`.`id` and ((`loggable_type` = 'fund_request' and `loggable_id` = 970) or (`loggable_type` = 'fund_request_record' and `loggable_id` in (SELECT `id` FROM `fund_request_records` WHERE `fund_request_id` = 970))))
```
added …

Add index on email_logs.mailable

---

tests/Browser/ProductReservationTest.php
tests/Feature/MollieExtraPaymentsTest.php
tests/Feature/ProductReservationTest.php
tests/Feature/VouchersProviderMeAppTest.php
tests/Traits/MakesTestFundProviders.php
tests/Traits/MakesTestFunds.php
tests/Traits/MakesTestOrganizations.php

Case: https://github.com/teamforus/forus-backend/actions/runs/12279849695/attempts/1
Fixed by creating a new fund during the test instead of using the seed data.

fix flaky test case

---

app/Http/Controllers/Api/Platform/Organizations/Sponsor/TransactionsController.php
app/Http/Requests/Api/Platform/Organizations/Sponsor/Transactions/StoreTransactionBatchRequest.php
app/Models/Voucher.php
app/Policies/VoucherPolicy.php
app/Providers/RouteServiceProvider.php
database/migrations/2024_11_04_113416_add_unique_key_to_number_on_vouchers_table.php
tests/Browser/VoucherTransactionBatchTest.php
tests/Feature/VoucherTransactionBatchTest.php

All voucher types should now have a unique number.
Uploading transactions bulk should now use voucher_number instead of voucher_id.

add number to product vouchers and upload transactions by voucher number

---

tests/Browser/Traits/HasFrontendActions.php

fix dusk tests for url stored filters

---

app/Models/Voucher.php
app/Rules/ProductReservations/ProductIdToReservationRule.php

disable extra payment reservations from subsidy products

---

app/Policies/FundPolicy.php

fix fund application when digid is optional
